### ISSUE TITLE
E1 Pro PTZ not working

### ISSUE THREAD

**Issue by FabioEight** [AlexxIT/WebRTC#127]
Hello, I've configured my E1 Pro using WebRTC, but following the PTZ config wiki, but no luck. Any hint?
Thanks

**Comment by Barma-lej** [comment]
Change `camera.reolink_e1_pro_profile000_mainstream` to your camera and try it:
```
type: custom:webrtc-camera
entity: camera.reolink_e1_pro_profile000_mainstream
webrtc: false
ptz:
  service: onvif.ptz
  data_left:
    entity_id: camera.reolink_e1_pro_profile000_mainstream
    pan: LEFT
    move_mode: ContinuousMove
  data_right:
    entity_id: camera.reolink_e1_pro_profile000_mainstream
    pan: RIGHT
    move_mode: ContinuousMove
  data_up:
    entity_id: camera.reolink_e1_pro_profile000_mainstream
    tilt: UP
    move_mode: ContinuousMove
  data_down:
    entity_id: camera.reolink_e1_pro_profile000_mainstream
    tilt: DOWN
    move_mode: ContinuousMove
  data_zoom_in:
    entity_id: camera.reolink_e1_pro_profile000_mainstream
    zoom: ZOOM_IN
    move_mode: ContinuousMove
  data_zoom_out:
    entity_id: camera.reolink_e1_pro_profile000_mainstream
    zoom: ZOOM_OUT
    move_mode: ContinuousMove
```
