### ISSUE TITLE
Simplify custom PTZ controls

### ISSUE THREAD

**Issue by Vinndimon** [AlexxIT/WebRTC#147]
I use a Chinese camera with XMEYE/Sofia. Its' PTZ is controlled with some Python scripts that look like this in my config:
```
#Street Camera PTZ control
shell_command:
  street_turn_right: python3 /config/python-dvr/right.py
  street_turn_left: python3 /config/python-dvr/left.py
  street_turn_up: python3 /config/python-dvr/up.py
  street_turn_down: python3 /config/python-dvr/down.py
```

Is it possible to just add shell commands as PTZ controls? Without extra complications such as creating scripts and services? Could you explain how to add my scripts into your integration's PTZ config?
