### ISSUE TITLE
PTZ, Zoom config for the reolink E1 Zoom

### ISSUE THREAD

**Issue by Barma-lej** [AlexxIT/WebRTC#167]
Hi Alex.
There is a config for the **reolink E1 Zoom**.
The integration works great with PTZ, Zoom and Sound. Thank you
```
type: custom:webrtc-camera
entity: camera.reolink_e1_zoom_profile000_mainstream
webrtc: false
ptz:
  service: onvif.ptz
  data_left:
    entity_id: camera.reolink_e1_zoom_profile000_mainstream
    pan: LEFT
    move_mode: ContinuousMove
  data_right:
    entity_id: camera.reolink_e1_zoom_profile000_mainstream
    pan: RIGHT
    move_mode: ContinuousMove
  data_up:
    entity_id: camera.reolink_e1_zoom_profile000_mainstream
    tilt: UP
    move_mode: ContinuousMove
  data_down:
    entity_id: camera.reolink_e1_zoom_profile000_mainstream
    tilt: DOWN
    move_mode: ContinuousMove
  data_zoom_in:
    entity_id: camera.reolink_e1_zoom_profile000_mainstream
    zoom: ZOOM_IN
    move_mode: ContinuousMove
  data_zoom_out:
    entity_id: camera.reolink_e1_zoom_profile000_mainstream
    zoom: ZOOM_OUT
    move_mode: ContinuousMove
```
