### ISSUE TITLE
Horizontal Stack

### ISSUE THREAD

**Issue by andiukas** [AlexxIT/WebRTC#170]
Hi, I have a problem, when I add to horizontal stack ptz cameras with webrtc,  ptz function not working. Any ideas ? 
I need multiple cameras in one line.

```
 - type: custom:button-card
        icon: mdi:cctv
        tap_action:
          action: call-service
          service: browser_mod.popup
          service_data:
            title: Kameros
            hide_header: true
            large: true
            card:
              type: horizontal-stack
              cards:
                - type: custom:webrtc-camera
                  entity: camera.sonoff_camera
                  ptz:
                    opacity: 0.4
                    service: sonoff.send_command
                    data_up:
                      device: 'xxxxxx'
                      cmd: up
```
