### ISSUE TITLE
[Bug]: custom shortcuts and title overlap

### ISSUE THREAD

**Issue by amitkeret** [AlexxIT/WebRTC#212]
The new custom shortcuts added in PR #169 create a layout issue.
They overlap with the title, if it is configured.

![image](https://user-images.githubusercontent.com/1258597/146362228-a0fb8b51-e2d5-45e6-af14-5af1a3a4fbf5.png)

```yaml
type: custom:webrtc-camera
entity: camera.sd
title: Dining Room
ui: true
shortcuts:
  - name: Record
    icon: mdi:record-circle-outline
    service: switch.toggle
    service_data:
      entity_id: switch.camera_record
```

**Comment by AlexxIT** [comment]
@dmamontov

**Comment by dmamontov** [comment]
Yeah, I'll fix it in the evening.

**Comment by dmamontov** [comment]
Fixed) https://github.com/AlexxIT/WebRTC/pull/214

**Comment by Napalmcold** [comment]
I did edited webrtc-camera.js accordingly to #214. Still can't change position of shortcut.
This config doesn't show any shotcuts:

```
type: custom:webrtc-camera
entity: camera.hall_camera
ui: true
shortcuts:
  top: 0
  left: 0
  orientation: vertical
  services:
    - name: Open
      icon: mdi:lock-open
      service: button.press
      service_data:
        entity_id: button.hall_unlocker
background: true
```
This one shows shortcut overlaped with title:
```
type: custom:webrtc-camera
entity: camera.ulitsa_camera
title: Вход с улицы
background: true
ui: true
shortcuts:
  - name: Open
    icon: mdi:lock-open
    service: button.press
    service_data:
      entity_id: button.ulitsa_unlocker
```

**Comment by amitkeret** [comment]
@Napalmcold 
seems like #214 hasn't been added to a release yet.
once @AlexxIT releases v2.2.1 you'll be able to pull it and use the new configuration
otherwise use `master` branch directly

**Comment by Napalmcold** [comment]
The deal is that I am using master. Removed webrtc integration completely And installed the master.

**Comment by dmamontov** [comment]
@Napalmcold Try clearing your browser cache

**Comment by dmamontov** [comment]
for example:
![image](https://user-images.githubusercontent.com/5955726/150980101-4118dc2e-54a2-4c48-8243-ef0bc1a9d795.png)

**Comment by Napalmcold** [comment]
> for example: ![image](https://user-images.githubusercontent.com/5955726/150980101-4118dc2e-54a2-4c48-8243-ef0bc1a9d795.png)

As soon as add lines "top, left, orientation, services", buttons just dissapear

**Comment by dmamontov** [comment]
@Napalmcold The behavior is very similar to the fact that you have an old script either in hass or cached in the browser, check in another browser (in the browser, not in the application)

**Comment by Napalmcold** [comment]
Ok, I managed it. Indeed it was cache as for the Chrome browser and for the android app.
Now I've noticed another issue: position of shortcuts differs depending on resolution of the screen (laptop or mobile app). 
Here are some example of the same card on different devices:
![image](https://user-images.githubusercontent.com/32687587/151353317-59f27daa-4c26-4b23-8058-478546b65f8a.png)
![image](https://user-images.githubusercontent.com/32687587/151353751-5fc71af0-17f2-46ee-8852-3d65eed52fa6.png)

**Comment by dmamontov** [comment]
@Napalmcold it is in pixels because. in theory, it can be modified so that it is possible to transfer the unit of measurement and some kind of% or vh.

**Comment by dmamontov** [comment]
@Napalmcold in the next PR added the ability to use padding in other css units, be it % or vh https://github.com/AlexxIT/WebRTC/pull/245

**Comment by Napalmcold** [comment]
@dmamontov, видимо можем по-русски)
Поправил код в соответствии с PR, но всё равно не могу понять, как указать положиние ровно по середине на разных экранах. Что px что vh делают одно и то же. Может нужно переставить master?

**Comment by dmamontov** [comment]
@Napalmcold 
1. Смотрим размер блока
![image](https://user-images.githubusercontent.com/5955726/151540019-9d074012-b873-4543-84ff-ef5233568220.png)
2. Добавляем расчет:
```yaml
shortcuts:
  left: calc(50% - 12px - 48px)
  services:
```
где 48px это половина ширины из 1 пункта.
