### ISSUE TITLE
Use entities instead of shortcuts (Feature request)

### ISSUE THREAD

**Issue by M4TH76** [AlexxIT/WebRTC#228]
Hi 
Could you implement the same functionality as picture-glance card "entities" instead of "shortcuts"

Thank you for this work of art!

Example:
```
type: custom:webrtc-camera
entity: camera.tapo_hd
entities:
  - entity: camera.tapo_hd
    icon: mdi:arrow-up-drop-circle-outline
    tap_action:
      action: call-service
      service: tapo_control.ptz
      service_data:
        entity_id: camera.tapo_hd
        tilt: UP
  - entity: camera.tapo_hd
    icon: mdi:eye-off-outline
    tap_action:
      action: call-service
      service: tapo_control.set_privacy_mode
      service_data:
        entity_id: camera.tapo_hd
        privacy_mode: 'on'
    hold_action:
      action: call-service
      service: tapo_control.set_privacy_mode
      service_data:
        entity_id: camera.tapo_hd
        privacy_mode: 'off'
  - entity: binary_sensor.tapo_motion
```
