### ISSUE TITLE
Has the syntax for Shortcuts changed?  This was working before but not anymore...

### ISSUE THREAD

**Issue by hchung-PA** [AlexxIT/WebRTC#239]
```
        card:
          type: custom:webrtc-camera
          entity: camera.front_door
          mse: false
          title: Front Door
          ui: true
          shortcuts:
            services:
              - name: Stop
                icon: mdi:stop
                service: eufy_security.stop_p2p_livestream
                service_data:
                  entity_id: camera.front_door
```

Had this code working with a stop button to stop the Eufy stream but this button doesn't show up anymore for whatever reason....
