### ISSUE TITLE
Add Ezviz PTZ to PT config examples.

### ISSUE THREAD

**Issue by rodriguezvictor1990** [AlexxIT/WebRTC#329]
The integration with Ezviz PTZ (model C8C Lite in my case) is the following code:

```
type: custom:webrtc-camera
url: rtsp://admin:pass@192.168.1.123:554/channel80
ptz:
  service: ezviz.ptz
  data_left:
    entity_id: ...
    direction: left
    speed: 5
  data_right:
    entity_id: ...
    direction: right
    speed: 5
  data_up:
    entity_id: ...
    direction: up
    speed: 5
  data_down:
    entity_id: ...
    direction: down
    speed: 5
```
speed : *(Optional) Speed to in which to move the camera. Allowed values: int from 1 to 9. Default: 5

No script needed. You need Ezviz integration installed.
