### ISSUE TITLE
HTML page support (for PiPup and others)

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/WebRTC#34]
Application: https://github.com/rogro82/PiPup
Video example: https://www.youtube.com/watch?v=j2tCamSDm7o

configuration.yaml

```yaml
rest_command:
  pipup:
    url: http://192.168.1.123:7979/notify
    content_type: 'application/json'
    verify_ssl: false
    method: 'post'
    timeout: 20
    payload: >
      {
      "duration": "{{ duration }}",
      "position": "{{ position }}",
      "title": "{{ title }}",
      "titleColor": "{{ titleColor }}",
      "titleSize": "{{ titleSize }}",
      "message": "{{ message }}",
      "messageColor": "{{ messageColor }}",
      "messageSize": "{{ messageSize }}",
      "backgroundColor": "{{ backgroundColor }}",
      "media": { "{{ mediaType }}": {
        "uri": "{{ uri }}", "width": "{{ width }}"
      }}
      } 
```

service call:

```
service: rest_command.pipup
data:
  title: ''
  message: Someone at the door...
  backgroundColor: '#DD000000'
  duration: 20
  messageColor: '#FFFFFF'
  messageSize: 20
  position: 2
  titleColor: '#50BFF2'
  titleSize: 15
  mediaType: web
  uri: 'http://192.168.1.111:8081'
  width: 640
```
