### ISSUE TITLE
PTZ Config Example for IMOU :)

### ISSUE THREAD

**Issue by mabusdogma** [AlexxIT/WebRTC#359]
Not an Issue really, more like good news:
PTZ control is (finally) supported in Imou Life cameras!
[Imou Life Integratión for Home Assistant](https://github.com/user2684/imou_life)

So maybe you guys find useful this WebRTC PTZ Config Example, tested on my camera

```
type: custom:webrtc-camera
url: rtsp://admin:secretkey@IP:554/cam/realmonitor?channel=1&subtype=1
muted: false
intersection: 1
ui: true
device_id: <your device ID>
ptz:
  service: imou_life.ptz_move
  data_left:
    device_id: <your device ID>
    duration: 100
    operation: LEFT
  data_right:
    device_id: <your device ID>
    duration: 100
    operation: RIGHT
  data_up:
    device_id: <your device ID>
    duration: 100
    operation: UP
  data_down:
    device_id: <your device ID>
    duration: 100
    operation: DOWN
  data_zoom_in:
    device_id: <your device ID>
    duration: 100
    operation: ZOOM_IN
  data_zoom_out:
    device_id: <your device ID>
    duration: 100
    operation: ZOOM_IN

```
