### ISSUE TITLE
Shortcuts do not appear in 2.3.1

### ISSUE THREAD

**Issue by wigster** [AlexxIT/WebRTC#362]
Just installed v2.3.1 on HA 2022.11.5 on HAOS. I have two TP-link cameras integrated through the TAPO Cameral Control integration. Browser: Edge on Windows and Safari on iOS.

I can see the camera streams fine, I have managed to get the PTZ pointing to work ok, however I cannot get the shortcuts to appear under any circumstances. Am I doing something wrong witht he config?

```yaml
type: custom:webrtc-camera
entity: camera.creepercam_salon_sd
ptz:
  service: button.press
  opacity: 0.4
  data_left:
    entity_id: button.salon_move_left
  data_right:
    entity_id: button.salon_move_right
  data_up:
    entity_id: button.salon_move_up
  data_down:
    entity_id: button.salon_move_down
shortcuts:
  top: 10
  left: 10
  services:
    - name: Privacy
      icon: mdi:eye
      service: switch.toggle
      service_data:
        entity_id: switch.salon_privacy
```
