### ISSUE TITLE
3.0 iOS Hass App opens fullscreen stream

### ISSUE THREAD

**Issue by macchrissli** [AlexxIT/WebRTC#388]
Since i updated the dashboard on the Hass iOS app always opens the webrtc stream to fullscreen mode. Makes it unusable to have as a card at the moment

**Comment by andker87** [comment]
same here, full-screen display automatically occurs even if you are not on the page where the cam previews are. I had to rollback to 2.3.1 because the home assistant app was unusable

**Comment by AlexxIT** [comment]
What iOS version do you use? Is WebRTC card on default page?

**Comment by andker87** [comment]
iOS 16.2 on iPhone X.
WebRTC is in a tab on the default dashboard, but not on the main page.

**Comment by PablaV** [comment]
I am also experiencing this on the companion app. Running iOS 16.2 on a iPhone 14 pro max.

**Comment by Yamaha0014** [comment]
I have the same problem, Iphone 13 pro and ios 16.2 last version WebRTC and go2rtc

**Comment by jason0x43** [comment]
I am also seeing this issue on an iPhone 13 Pro running iOS 16.2, Companion app 2022.10.1, and WebRTC 3.0.0. I have a dashboard page with 3 custom:webrtc-camera cards:

```yaml
cards:
  - type: custom:webrtc-camera
    entity: camera.cat_room
    muted: true
    ui: false
  - type: custom:webrtc-camera
    entity: camera.back_yard
    muted: true
    ui: false
  - type: custom:webrtc-camera
    entity: camera.garage
    muted: true
    ui: false
```

When the dashboard loads, the three camera cards start loading their streams. As each stream loads, it becomes full screen. I also have dashboard pages for each individual camera. The same thing happens on those -- as soon as the camera stream loads, the video becomes full screen.

This isn't 100% consistent. The video becoming full screen happens most of the time when I open a page with a webrtc-camera card, but not every time.
