### ISSUE TITLE
Some cameras stuck at loading2 status

### ISSUE THREAD

**Issue by FSciammarella** [AlexxIT/WebRTC#389]
I have 7 cameras connected using rtsp. All worked well under 2.x version. Upon updating to 3.0.0, some cameras work, some just display a blank screen and loading2. 6 of them are streams from a single NVR, using the same credentials, 3 work and 3 don't. The card is configured as follows:

```yaml
type: custom:webrtc-camera
url: rtsp://[USER]:[PW]@[NVR_IP]:554/cam/realmonitor?channel=[CHANNEL_NUM]&subtype=1
ui: true
```
