### ISSUE TITLE
Can't connect to self-host go2rtc server

### ISSUE THREAD

**Issue by addrum** [AlexxIT/WebRTC#403]
![image](https://user-images.githubusercontent.com/2855069/214696819-87ab5af8-8118-414c-96a8-935f2254fa8c.png)

I get this image. Using the built in server works fine but I need to modify the urls to use `#backchannel=0` but don't want to do this directly in the lovelace UI as I commit this to git so would have credentials exposed (connecting via generic camera also times out so I guess related? - also not ideal as I see it mentions poor latency in the go2rtc docs).

Weirdly the go2rtc ui at 1984 is accessible just fine. Can't load any cameras at 8554 though. I'm using docker network mode bridge, also tried host without success.

**Comment by addrum** [comment]
I'm getting this warning repeatedly in the docker logs `WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:205 > error=EOF`

**Comment by AlexxIT** [comment]
Can you open this URL in your browser?

**Comment by addrum** [comment]
Yep can access in the browser.

**Comment by addrum** [comment]
I _think_ the log messages are unrelated. I've just tried reinstalling the integration and then inputting the url, despite still getting the message in the screenshot, I'm not seeing the log messages when watching the docker logs this time.

**Comment by AlexxIT** [comment]
Is the problem still relevant?

**Comment by addrum** [comment]
@AlexxIT unfortunately, yes. Just tried redpeploying the container with the latest image on the latest HA and get the same error. I can still access the same url in the browser too.

Just for some added info, I'm running HA and go2rtc containers on the same machine if that helps.

**Comment by AlexxIT** [comment]
How you run containers? Show code

**Comment by addrum** [comment]
Docker compose.

```
version: "3"
services:
  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    environment:
      - PGID=65537
      - PUID=1029
      - TZ=Europe/London
    network_mode: bridge
    ports:
       - 1984:1984
       - 8554:8554
    restart: unless-stopped
    volumes:
      - "/volume1/docker/go2rtc/:/config/"
```

HA

```
version: "3.9"
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    environment:
      - PGID=65537
      - PUID=1029
      - TZ=Europe/London
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - /volume1/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
```
