### ISSUE TITLE
Selecting Stream 'Mode' for DashCast Service 

### ISSUE THREAD

**Issue by ZeeHammar** [AlexxIT/WebRTC#407]
For the life of me I haven't been able to determine if/how one can define the stream mode (like within the UI card) when using the dashcast service call. Is this possible, and if show how is it accomplished? 

I have the WebRTC mode defined for my cards as it is more response than MSE, which is what my stream defaults to if not defined. When using dashcast it also defaults to MSE and I'd like to be able to force it to WebRTC if possible.

**Comment by AlexxIT** [comment]
Card will prefer MSE over WebRTC if you stream has H265 or AAC codecs.
If your stream will have no audio or PCMU/PCMA/OPUS audio - card will use WebRTC technology

**Comment by AlexxIT** [comment]
```
service: webrtc.dash_cast
data:
  entity_id: media_player.nesthub
  url: rtsp://rtsp:12345678@192.168.1.123:554/av_stream/ch0
  extra:
    mode: webrtc
```
