### ISSUE TITLE
Dafang hack configuration

### ISSUE THREAD

**Issue by vlaraort** [AlexxIT/WebRTC#409]
Hi!

I have a hacked dafang camera that was working on the v2, and now in the v3 get stuck in "loading 2"

I see in the documentation that this camera sould work, but it indicates a configuration:

"Video: H264, size: 1920x1080, bitrate: 1000, format: VBR, frame rate: 10
Audio: PCMU, rate in: 8000, rate out: 44100"

That I dont really understand where I should set it up.

My camera configuration is:

```
camera:
  - platform: ffmpeg
    name: Living Room Camera
    input: -rtsp_transport tcp -i rtsp://192.168.1.141/unicast
```

and my card

```
          - type: "custom:webrtc-camera"
            entity: camera.living_room_camera
            title: 'Salón'
            ui: true
```

The camera streams works fine in home assistant, but the webRTC card is stuck. I have another camera of other platform (generic) that works fine. Can someone point me what can be the problem, and how/where should I set those configurations to check if this is the issue?

Thanks!
