### ISSUE TITLE
webrtc.create_link service no longer working

### ISSUE THREAD

**Issue by rpruden** [AlexxIT/WebRTC#416]
After changing to version 3 or above, the previously registered service called webrtc.create_link no longer works. I had previously been using an automation to create a URL which would open the stream. Is there an alternative service now available for this function? The YAML in my automation looks like this:

```
alias: Create Link - Camera Motion
sequence:
  - variables:
      link_id: cameramotion
      link_path: https://ha.url/webrtc/embed?url={{link_id}}
  - service: webrtc.create_link
    data:
      link_id: "{{ link_id }}"
      url: rtsp://localhost:38669/
      open_limit: 0
      time_to_live: 300
mode: single
```

It was working well previously, but now that go2rtc is implemented as the backend it no longer works. I have downgraded to 2.3 in th meantime and that has worked around the limitation.
