### ISSUE TITLE
Shortcut Has Been Pressed Feedback Indicator

### ISSUE THREAD

**Issue by haforme** [AlexxIT/WebRTC#430]
Hello, would it be possible to add functionality to the "custom:webrtc-camera" card so that when a shortcut icon is pressed a feedback entity could be associated with the shortcut that illuminates the icon. Thanks in advance for your consideration.

**Comment by AlexxIT** [comment]
I'm not best with JavaScript and don't plan to add a lot of additional functionality to card. 
I'm more involved with adding features to stream processing.

**Comment by roon7** [comment]
Hi, it would be very useful, e.g. to the state of the gate if the distance is too far to see, I have this on picture-elements card and motion-eye. Would like to change to your solution, but miss exactly this one.

  - entity: binary_sensor.gate_closed_contact
    icon: mdi:door-open
    style:
      '--paper-item-icon-color': green
      '--paper-item-icon-active-color': rgb(250,60,60)
    type: state-icon

**Comment by haforme** [comment]
Thanks for the feedback.  Just to clarify my thoughts if you had for example a shortcut that controls a switch then the state of the entity id would get reflect on the screen visually. Super useful to see the status of the action performed. 

shortcuts:
  - name: Barn Light
    icon: mdi:outdoor-lamp
    service: switch.toggle
    service_data:
      entity_id: switch.x10_on_off_switch_x10_b_01

**Comment by gtxaspec** [comment]
any solution to this yet? Would love to be able to change the icon upon click!

**Comment by AlexxIT** [comment]
I like the idea of using templates better. They're more universal. And can solve a lot of issues.
The problem is that existing components recreate the card when entities state changes. This causes the stream to restart.

```yaml
type: custom:config-template-card
entities:
  - input_boolean.test
card:
  type: custom:webrtc-camera
  url: tmp1
  background: true
  shortcuts:
    - name: Barn Light
      icon: >-
        ${ states['input_boolean.test'].state === 'on' ?
        'mdi:outdoor-lamp':'mdi:lamp' }
      service: input_boolean.toggle
      service_data:
        entity_id: input_boolean.test
```

```yaml
type: custom:card-templater
entities:
  - input_boolean.test
card:
  type: custom:webrtc-camera
  url: tmp1
  shortcuts:
    - name: Barn Light
      icon_template: >-
        {{ 'mdi:outdoor-lamp' if is_state('input_boolean.test', 'on')
        else'mdi:lamp' }}
      service: input_boolean.toggle
      service_data:
        entity_id: input_boolean.test
```
