### ISSUE TITLE
PTZ control throws error

### ISSUE THREAD

**Issue by baurmatt** [AlexxIT/WebRTC#433]
Hey,

I've got a Amcrest IP2M-841 and use the following lovelace card configuration:

```yaml
  - type: custom:webrtc-camera
    entity: camera.amcrest_camera
    muted: true
    ptz:
      service: amcrest.ptz_control
      data_left:
        entity_id: camera.amcrest_camera
        pan: left
      data_right:
        entity_id: camera.amcrest_camera
        pan: right
      data_up:
        entity_id: camera.amcrest_camera
        tilt: up
      data_down:
        entity_id: camera.amcrest_camera
        tilt: down
      data_zoom_in:
        entity_id: camera.amcrest_camera
        zoom: zoom_in
      data_zoom_out:
        entity_id: camera.amcrest_camera
        zoom: zoom_out
```

Webcam streaming works flawlessly, only the PTZ control strikes. Clicking on any of the PTZ buttons leads to the following error message:

> Failed to call service amcrest/ptz_control. extra keys not allowed @ data['pan']

I've enabled debug log of this extension, but nothing is logged.

I've confirmed that PTZ works by using the example from the integration page -> https://www.home-assistant.io/integrations/amcrest/#example-card-with-controls

Using v3.1.0 of the WebRTC custom component.
