### ISSUE TITLE
Question: How to configure PTZ with dafang ?

### ISSUE THREAD

**Issue by richiesgr** [AlexxIT/WebRTC#466]
Hi
I've followed the guide and add my config as described in https://github.com/AlexxIT/WebRTC/wiki/PTZ-Config-Examples#xiaomi-dafang-with-hack
I've install MQTT 
On my card I see the control buttons but nothing happen when using it
Do you've any idea ?
Thanks

**Comment by dbuezas** [comment]
```yaml
type: custom:webrtc-camera
url: rtsp://homeassistant.local:8554/dafang3
muted: false # up to you
intersection: 0 # otherwise it stops when in full screen in mobile
ui: true
ptz:
  service: mqtt.publish
  data_left:
    topic: myhome/dafang/motors/horizontal/set
    payload: left
  data_right:
    topic: myhome/dafang/motors/horizontal/set
    payload: right
  data_up:
    topic: myhome/dafang/motors/vertical/set
    payload: up
  data_down:
    topic: myhome/dafang/motors/vertical/set
    payload: down
shortcuts:
  top: 0
  left: 0
  orientation: vertical
  services:
    - name: Record
      icon: mdi:reload-alert
      service: script.turn_on
      service_data:
        entity_id: script.calibrate_dafang_camera_plz
    - name: IR Light
      icon: mdi:brightness-7
      service: switch.toggle
      service_data:
        entity_id: switch.dafang_night_mode
```

And this script for the calibration via button.

```yaml
alias: Calibrate dafang camera PLZ
sequence:
  - service: cover.set_cover_position
    target:
      entity_id:
        - cover.dafang_move_left_right
        - cover.dafang_move_up_down
    data:
      position: 100
  - service: cover.set_cover_position
    target:
      entity_id:
        - cover.dafang_move_left_right
        - cover.dafang_move_up_down
    data:
      position: 50
mode: single
```
