### ISSUE TITLE
404, message='Invalid response status'

### ISSUE THREAD

**Issue by sgurgul** [AlexxIT/WebRTC#469]
I have setup with:
- HA 2023.4.4
- Frigate 0.12 installed on a separate device, using docker-composer 
- Frigate NVR Proxy 1.3 addon in HA 
- go2rtc configured inside Frigate
- Dahua cameras which I would like to monitor using 'custom:webrtc-camera' card

Frigate, proxy addon and go2rtc seem to be working fine:
- I am able to see camera views in Frigate addon UI in HA
- For each configured camera I can successfully choose mse/webrts/jsmpeg and for mse and webrtc I get a high resolution real-time views

Issue starts when I am trying to configure 'custom:webrtc-camera' card.

I get a constant "404, message='Invalid response status'" error message which does not give me any hints what do I do wrong.
![image](https://user-images.githubusercontent.com/6459421/231897582-997455b0-44ea-47e0-8c67-81ed4987431a.png)

Since I am able to see cameras real-time view in Frigate addon UI I guess streams configuration, access matters, etc. are rather fine.

Configuration is:
* Frigate host: 192.168.1.102
* HA: 192.168.1.105
* WebRTC integration added to HA with following go2rtc server URL: http://192.168.1.102:5000

Docker Composer script:
```
frigate:
  container_name: frigate
  privileged: true 
  restart: unless-stopped
  image: ghcr.io/blakeblackshear/frigate:stable
  shm_size: "216mb" 
  devices:
    - /dev/bus/usb:/dev/bus/usb 
    - /dev/dri/renderD128 
  volumes:
    - /etc/localtime:/etc/localtime
    - /home/sebo/frigate/config.yml:/config/config.yml
  ports:
    - "5000:5000"
    - "8554:8554"     # RTSP feeds
    - "8555:8555/tcp" # WebRTC over TCP
    - "8555:8555/udp" # WebRTC over UDP
  environment:
    FRIGATE_RTSP_PASSWORD: "***"
```

Frigate go2rtc configuration:
```
go2rtc:
  streams:
    frigate_schody:
      - rtsp://admin:***@192.168.1.134
```

'custom:webrtc-camera' card configuration:
```
type: custom:webrtc-camera
url: rtsp://admin:***@192.168.1.134
title: Schody
```

Using camera entity ID directly in the card should be also possible, as far as I understand docs:
```
type: custom:webrtc-camera
entity: camera.frigate_schody
title: Schody
```

But if I do I just get another error:
"Can't get URL for camera.frigate_schody"
![image](https://user-images.githubusercontent.com/6459421/231896666-37a57c00-61e3-4442-b3f1-e0b73b254581.png)

Is it like the 'custom:webrtc-camera' is not yet ready for new Frigate/go2rtc configuration and will require some updates ?

Or do I do something very wrong ?
