### ISSUE TITLE
Digital zoom controls (via css)

### ISSUE THREAD

**Issue by dbuezas** [AlexxIT/WebRTC#482]
I have been wanting to have a "fake"/digital zoom for my cameras for a while. It would be a really cool feature if this card could do that (maybe even full fake ptz).

But in the meanwhile, here's a way to add it via yaml. It even works in full screen :) 

# Digital zoom in the card
![Kapture 2023-05-01 at 22 22 44](https://user-images.githubusercontent.com/777196/235524631-d9fec3aa-da3b-42d7-9125-023744666f15.gif)

# Instructions
### 2. Create a number helper from [![Open your Home Assistant instance and show your helper entities.](https://my.home-assistant.io/badges/helpers.svg)](https://my.home-assistant.io/redirect/helpers/)
<img width="416" alt="image" src="https://user-images.githubusercontent.com/777196/235525031-aa6bd278-7846-48c1-8631-335c1fa7cf3f.png">

### 3. Modify the yaml of your webrtc-camera like this

```yaml
type: custom:webrtc-camera
url: my_camera
card_mod:
  style: |
    ha-card .player {
      transition: transform 200ms;
      transform: scale({{2**(states('input_number.zoom')|float-1)}});
    }
shortcuts:
  services:
    - name: Zoom in
      icon: mdi:magnify-plus
      service: input_number.increment
      service_data:
        entity_id: input_number.zoom
    - name: Zoom out
      icon: mdi:magnify-minus
      service: input_number.decrement
      service_data:
        entity_id: input_number.zoom
```
(of course you can use the same input_number for multiple cameras)
