### ISSUE TITLE
[Solution] PTZ for ICSee/DVR-IP/NetSurveillance/Sofia cameras

### ISSUE THREAD

**Issue by dbuezas** [AlexxIT/WebRTC#495]
I'd add it to the wiki myself, but I think there's no way to make PRs to wikis.
Combined with the [DVRIP source](https://github.com/AlexxIT/go2rtc#source-dvrip) in go2rtc, this means that ICSee cameras that don't have onvif can work very well in Home Assistant.

Here's thee integration that exposes PTZ services: 
--> https://github.com/dbuezas/icsee-ptz <--

Full yamls in the repo, but this how the PTZ can then be configured in this wonderful WebRTC card
```yaml
ptz:
  service: icsee_ptz.move
  data_left:
    host: 192.168.178.27
    password: camarablanca3
    move_time: 1 # 1 second
    step: 10 # fastest speed
    cmd: DirectionRight
...
```
