### ISSUE TITLE
mse: wrong response on DESCRIBE and mse: wrong user/pass

### ISSUE THREAD

**Issue by HaunsTM** [AlexxIT/WebRTC#499]
I have an odd problem with my HA setup.  Sometimes webrtc reports mse: wrong response on DESCRIBE, another intermittent odd error "mse: wrong user/pass".
![image](https://github.com/AlexxIT/WebRTC/assets/10531742/71309991-fe7f-4fd8-a4c3-30e0745d3ae7)

In my network I have several cameras:

1 x D-link
2 x Tapo C310
3 x Tapo C320WS

My setup is
```
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

HACS Integration version:  1.32.1
```

This is my entire  /config/go2rtc.yaml:
```
  bird_feeder:
    - rtsp://{USER}:{PASSWORD}@10.0.0.30:554/stream2

  outdoor_room:
    - rtsp://{USER}:{PASSWORD}@10.0.0.31:554/stream2

  garage:
    - rtsp://{USER}:{PASSWORD}@10.0.0.32/live1.sdp

  hen_house_sleep:
    - rtsp://{USER}:{PASSWORD}@10.0.0.35:554/stream2

  hen_house_room:
    - rtsp://{USER}:{PASSWORD}@10.0.0.33:554/stream2

  hen_yard:
    - rtsp://{USER}:{PASSWORD}@10.0.0.34:554/stream2

  garage_driveway:
    - rtsp://{USER}:{PASSWORD}@10.0.0.36:554/stream2

### This will generate a debugging level log for Go2RTC ###
log:
  level: trace
  api: debug
  exec: debug
  ngrok: debug
  rtsp: trace
  streams: debug
  webrtc: debug
```

My issue is with my newly added outdoor room and bird feeder cameras. A Tapo C320WS. 

Facts:
* I do not have any other issues with any other cameras. They work as expedcted!
* I can successfully open _every_ network stream from yaml-file with VLC at _*any time*_

I have rebooted camera + router + HA (raspberry pi 4+ 8GB). Then it works for about 5-10 min until i refresh my browser (hitting 'F5' in Chrome). After that I can get different types of errors  (without changing anything):

* mse: wrong response on DESCRIBE
* mse: wrong user/pass

The log below is from when go2rtc states "mse: wrong user/pass" (I'm still using correct user password and user) 
```
Cseq: 2
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.115 TRC [rtsp] describe (backchannel=true) err: wrong user/pass
18:04:08.118 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Accept: application/sdp
User-Agent: go2rtc/1.5.0
CSeq: 3

18:04:08.124 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 3
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.125 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Accept: application/sdp
User-Agent: go2rtc/1.5.0
CSeq: 4
Authorization: Basic ----

18:04:08.132 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 4
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.132 DBG [webrtc] add consumer error="wrong user/pass"
18:04:08.135 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Accept: application/sdp
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.5.0
CSeq: 1

18:04:08.143 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 1
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.143 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.5.0
CSeq: 2
Authorization: Basic ----

Accept: application/sdp

18:04:08.148 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Www-Authenticate: Basic realm="TP-LINK IP-Camera"
Cseq: 2
Date: Sat, Jun 10 2023 16:04:07 GMT

18:04:08.148 TRC [rtsp] describe (backchannel=true) err: wrong user/pass
18:04:08.150 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Accept: application/sdp
User-Agent: go2rtc/1.5.0
CSeq: 3

18:04:08.159 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 3
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.159 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Authorization: Basic ----
Accept: application/sdp
User-Agent: go2rtc/1.5.0
CSeq: 4

18:04:08.163 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"
Cseq: 4

18:04:08.164 DBG [streams] can't stop none producer
18:04:08.164 DBG [streams] can't stop none producer
18:04:08.164 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:177 > error="wrong user/pass"
```

The weird thing: I can successfully copy the `rtsp://...`s from go2rtc.yaml-file (above) and open them with separate VLC at any time. Whats the problem here?

**Comment by HaunsTM** [comment]
I have an odd problem with my HA setup.  Sometimes webrtc reports mse: wrong response on DESCRIBE, another intermittent odd error "mse: wrong user/pass".
![image](https://github.com/AlexxIT/WebRTC/assets/10531742/71309991-fe7f-4fd8-a4c3-30e0745d3ae7)

In my network I have several cameras:

1 x D-link
2 x Tapo C310
3 x Tapo C320WS

My setup is
```
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

HACS Integration version:  1.32.1
```

This is my entire  /config/go2rtc.yaml:
```
  bird_feeder:
    - rtsp://{USER}:{PASSWORD}@10.0.0.30:554/stream2

  outdoor_room:
    - rtsp://{USER}:{PASSWORD}@10.0.0.31:554/stream2

  garage:
    - rtsp://{USER}:{PASSWORD}@10.0.0.32/live1.sdp

  hen_house_sleep:
    - rtsp://{USER}:{PASSWORD}@10.0.0.35:554/stream2

  hen_house_room:
    - rtsp://{USER}:{PASSWORD}@10.0.0.33:554/stream2

  hen_yard:
    - rtsp://{USER}:{PASSWORD}@10.0.0.34:554/stream2

  garage_driveway:
    - rtsp://{USER}:{PASSWORD}@10.0.0.36:554/stream2

### This will generate a debugging level log for Go2RTC ###
log:
  level: trace
  api: debug
  exec: debug
  ngrok: debug
  rtsp: trace
  streams: debug
  webrtc: debug
```



My issue is with my newly added outdoor room and bird feeder cameras. A Tapo C320WS. 

Facts:
* I do not have any other issues with any other cameras. They work as expedcted!
* I can successfully open _every_ network stream from yaml-file with VLC at _*any time*_

I have rebooted camera + router + HA (raspberry pi 4+ 8GB). Then it works for about 5-10 min until i refresh my browser (hitting 'F5' in Chrome). After that I can get different types of errors  (without changing anything):

* mse: wrong response on DESCRIBE
* mse: wrong user/pass

The log below is from when go2rtc states "mse: wrong user/pass" (I'm still using correct user password and user) 
```
Cseq: 2
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.115 TRC [rtsp] describe (backchannel=true) err: wrong user/pass
18:04:08.118 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Accept: application/sdp
User-Agent: go2rtc/1.5.0
CSeq: 3

18:04:08.124 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 3
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.125 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Accept: application/sdp
User-Agent: go2rtc/1.5.0
CSeq: 4
Authorization: Basic ----

18:04:08.132 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 4
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.132 DBG [webrtc] add consumer error="wrong user/pass"
18:04:08.135 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Accept: application/sdp
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.5.0
CSeq: 1

18:04:08.143 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 1
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.143 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.5.0
CSeq: 2
Authorization: Basic ----

Accept: application/sdp

18:04:08.148 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Www-Authenticate: Basic realm="TP-LINK IP-Camera"
Cseq: 2
Date: Sat, Jun 10 2023 16:04:07 GMT

18:04:08.148 TRC [rtsp] describe (backchannel=true) err: wrong user/pass
18:04:08.150 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Accept: application/sdp
User-Agent: go2rtc/1.5.0
CSeq: 3

18:04:08.159 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 3
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"

18:04:08.159 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.31:554/stream2 RTSP/1.0
Authorization: Basic ----
Accept: application/sdp
User-Agent: go2rtc/1.5.0
CSeq: 4

18:04:08.163 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Date: Sat, Jun 10 2023 16:04:07 GMT
Www-Authenticate: Basic realm="TP-LINK IP-Camera"
Cseq: 4

18:04:08.164 DBG [streams] can't stop none producer
18:04:08.164 DBG [streams] can't stop none producer
18:04:08.164 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:177 > error="wrong user/pass"
```

The weird thing: I can successfully copy the `rtsp://...`s from go2rtc.yaml-file (above) and open them with separate VLC at any time. Whats the problem here?
