### ISSUE TITLE
Bug: Shortcuts not working

### ISSUE THREAD

**Issue by gtxaspec** [AlexxIT/WebRTC#502]
console error upon shortcut click:
```
webrtc-camera.js?v3.1.0:436 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at HTMLDivElement.<anonymous> (webrtc-camera.js?v3.1.0:436:50)
(anonymous) @ webrtc-camera.js?v3.1.0:436
```

example code that causes it:
```
type: custom:webrtc-camera
url: rtsp://10.xx.xx.x:8554/camera-sub
poster: https://home-assistant.io/images/cast/splash.png
background: true
muted: true
mode: webrtc
ui: true
shortcuts:
  - name: Snapshot
    icon: mdi:eye
service: telegram_bot.send_video
data:
  url: >-
    http://10.xx.xx.x:1984/api/frame.mp4?src=rtsp://10.xx.xx.x:8554/camera-sub
  target:
    - xxxx
    - xxxx
```

**Comment by gtxaspec** [comment]
correcting indents:
```
type: custom:webrtc-camera
url: rtsp://xxx
poster: https://home-assistant.io/images/cast/splash.png
background: true
muted: true
mode: webrtc
ui: false
shortcuts:
  - name: Snapshot
    icon: mdi:eye
    service: telegram_bot.send_video
    data:
      url: xxx
      target: xxx
```
gives an error in the logs:
```

Jun 13 09:51:49 haos homeassistant[258]: 2023-06-13 09:51:49.052 WARNING (SyncWorker_5) [homeassistant.components.telegram_bot] Can't load data. No data found in params!
Jun 13 09:51:49 haos homeassistant[258]: 2023-06-13 09:51:49.062 ERROR (SyncWorker_5) [homeassistant.components.telegram_bot] Can't send file with kwargs: {}
```
is there something i'm missing from the example code?
