### ISSUE TITLE
SD/HD toggle

### ISSUE THREAD

**Issue by dbuezas** [AlexxIT/WebRTC#523]
When on the go I often miss the option to switch to a lower resolution stream.
I intend to work on a PR that adds a config option `url_sd`. When present, the UI will add a new button that will toggle between `SD` and `HD` and switch between the streams.

What do you think?

**Comment by AlexxIT** [comment]
I don't think it should be url_sd.

I think it should be list of URLs and modes. User can click on mode label for switch to next item. Or some drop down should appear.
When new url+mode selected - card should restart connection process.

This realisation will close many cases.

**Comment by dbuezas** [comment]
Something like this?
```yaml
streams:
  - url: rtsp://high-res
    name: hd
  - url: rtsp://low-res
    name: sd
```
or 

```yaml
urls:
  hd: rtsp...
  sd: rtsp...
  other: rtsp...
```
?

**Comment by AlexxIT** [comment]
Yes. And `mode: webrtc...` may be useful

**Comment by direx1** [comment]
> I don't think it should be url_sd.
> 
> I think it should be list of URLs and modes. User can click on mode label for switch to next item. Or some drop down should appear. When new url+mode selected - card should restart connection process.
> 
> This realisation will close many cases.

This and the example below your comment would be really useful. Currently I use a shortcut button to run a browser_mod popup with a high res stream but this would perhaps be better.

**Comment by dbuezas** [comment]
The linked PR implements this, it will probably land in master sooner or later :)

**Comment by dbuezas** [comment]
I correct myself: _"later rather than sooner"_ 😆

**Comment by AlexxIT** [comment]
Oh, sorry. Was on holidays two weeks.

**Comment by dbuezas** [comment]
Hehe, I'm joking! :)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.3.0

**Comment by marcob79** [comment]
I try this new interesting function, but it is not clear how to do the switch :)
I dind't see also the name assigned to the 2 url

```
type: custom:webrtc-camera
streams:
  - url: camera.go_box
    name: HD
  - url: camera.go_sala
    muted: true
    name: SD
```
