### ISSUE TITLE
`muted` option makes no difference

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/WebRTC#529]
I'm using the latest (3.2.1), and the `muted` option simply makes no difference: the audio is always muted no matter what:

https://github.com/AlexxIT/WebRTC/assets/29582865/d61583c3-771b-4597-bcb7-afd4bd09effa

**Comment by felipecrs** [comment]
@AlexxIT if I change the following lines:

https://github.com/AlexxIT/WebRTC/blob/359e3ecea9ddbda100c248b812b7f16a05e3732d/custom_components/webrtc/www/video-rtc.js#L161-L165

To:

```diff
            if (!this.video.muted) {
-               this.video.muted = true;
+               this.video.muted = false;
                this.video.play().catch(er => {
                    console.warn(er);
                });
```

Then the audio starts unmuted, but it also starts paused by default.

**Comment by felipecrs** [comment]
Ok, I think I understood what that piece of code is doing. It's actually falling back to muted audio if Chrome's autoplay block is detected.

I just don't understand why it works in go2rtc's stream page normally, and also why it works with Frigate Card.

**Comment by alexcodito** [comment]
Facing the same issue

**Comment by felipecrs** [comment]
One workaround is to use the WebRTC card within the Frigate Card, with the Frigate Card configured to auto unmute.

**Comment by AlexxIT** [comment]
This is a very complex and confusing issue. Different browsers allow audio for completely different reasons.
This may depend on how the page is opened (whether the user clicked somewhere) and how often the user opens the page.
If it worked on the old version and stopped working on the new version - you need to run some tests and understand the difference in JS code.

**Comment by stplatt** [comment]
I'm seeing it in chrome and android webview. It works ok with version 3.1.1, the issue started with 3.2.1. I downgraded to 3.1.1 and it's working as expected again

**Comment by mikedrawback** [comment]
Same here, had to downgrade to 3.1.1

**Comment by Mr-HaleYa** [comment]
The Chrome update broke a lot of platforms auto-play. I use Pandora radio on my desktop through Chrome and even they added a thing recently saying autoplay may be broken but as you use the site more then Chrome will "learn" what you want and autoplay should start functioning again as normal.
<img width="531" alt="image" src="https://github.com/AlexxIT/WebRTC/assets/42821995/7b56153a-16e5-43ef-be82-708b120b95f3">

**Comment by AlexxIT** [comment]
@Mr-HaleYa where you get this screenshot?

**Comment by Mr-HaleYa** [comment]
At the bottom of this page
https://help.pandora.com/s/article/Chrome-Troubleshooting-1519949296244?language=en_US

**Comment by a20691** [comment]
> The Chrome update broke a lot of platforms auto-play. I use Pandora radio on my desktop through Chrome and even they added a thing recently saying autoplay may be broken but as you use the site more then Chrome will "learn" what you want and autoplay should start functioning again as normal. <img alt="image" width="531" src="https://user-images.githubusercontent.com/42821995/263440794-7b56153a-16e5-43ef-be82-708b120b95f3.png">

This happened to me.  At first it was never unmuted, after a few hours trying to get around the situation it started to work perfectly, after two days without using it, it didn't work again.  So it makes sense to be some kind of Chrome memory function.

**Comment by luzik** [comment]
I have 4 webrtc cards with:
```
muted: true
mode: webrtc
```
On every browser refresh mute icon is muted or unmuted (seams random) - independently from other cards

uuuu
umuu
umum
uuuu
uumu
..just random on every browser refresh

unmuted cards do not play any sound, and pressing mute button do not change anything (even icon do not change to muted state)
Firefox here

**Comment by Takst3in** [comment]
Hi all!

I'm casting a webrtc_camera card on a dashboard in panel mode, to my Nest Hub, as a baby-cam stream.
The stream always comes up with the "muted ON button", I have to press the mute button to get sound.

Suspect this is related to this bug, however downgrading to other versions (3.2.1/3.2.0/3.1.1) does not resolve the issue, 
also editing the line (true/false) "this.video.muted = true;" in /webrtc/www/video-rtc.js file also does not make any difference.

I'm casting the dashboard via DashCast (HA Continuesly Casting Dashboard) integration.

**Comment by stplatt** [comment]
Workaround is to use the [Frigate card](https://github.com/dermotduffy/frigate-hass-card) with the webrtc-card provider. The mute settings work properly with that setup

**Comment by Takst3in** [comment]
> Workaround is to use the [Frigate card](https://github.com/dermotduffy/frigate-hass-card) with the webrtc-card provider. The mute settings work properly with that setup

Do you have a template configuration for that setup?

**Comment by felipecrs** [comment]
This is the one I use:

The dashboard:

```yaml
views:
  - title: Home
    type: panel
    badges: []
    cards:
      - type: custom:frigate-card
        cameras:
          - live_provider: webrtc-card
            webrtc_card:
              url: camera_03
              style: |
                video {aspect-ratio: 16/9; object-fit: fill;}
                .mode {display: none}
            camera_entity: camera.video_porteiro
        view:
          default: live
        live:
          auto_play: all
          auto_unmute: all
          controls:
            builtin: false
            title:
              mode: none
          zoomable: true
          layout:
            fit: cover
            position:
              x: 0
              'y': 0
          lazy_unload: all
        menu:
          buttons:
            cameras:
              enabled: false
            frigate:
              enabled: false
            fullscreen:
              enabled: false
            media_player:
              enabled: false
            play:
              enabled: true
            microphone:
              enabled: false
            live:
              enabled: false
            mute:
              enabled: true
          style: overlay
          position: top
          alignment: right
          button_size: 80
        dimensions:
          aspect_ratio_mode: static
          aspect_ratio: '16:9'
        elements:
          - type: custom:frigate-card-menu-state-icon
            entity: cover.porta
            tap_action:
              action: toggle
            priority: 51
        performance:
          profile: low
```

How I can the service:

```yaml
service: cast.show_lovelace_view
data:
  entity_id: media_player.sala_home
  view_path: "0"
  dashboard_path: video-porteiro
```

The result:

https://github.com/dermotduffy/frigate-hass-card/assets/29582865/e0e77aea-e555-4978-8e7b-20a745034e1a

Refs https://github.com/dermotduffy/frigate-hass-card/issues/1231
