### ISSUE TITLE
v1.6.1: Stream Name in webrtc HA component configuration doesn't work anymore

### ISSUE THREAD

**Issue by alexdelprete** [AlexxIT/WebRTC#536]
I was using go2rtc with HA webrtc component, a simple lovelace card config with stream name, and it was working beautifully with v1.6.0.

```yaml
type: custom:webrtc-camera
url: doorbell_main
ui: true
poster: https://home-assistant.io/images/cast/splash.png
muted: true
intersection: 0.75
background: false
style: >-
  .header {top: unset; bottom: 0px} .mode {position: absolute; bottom: 30px}
  .shortcuts {left: unset; top: 25px; right: 5px; display: flex; flex-direction:
  column}
mode: webrtc,mse,mp4
shortcuts:
  - name: Pedonale
    icon: mdi:door-closed-lock
    service: switch.toggle
    service_data:
      entity_id: switch.switch_pedonale
```

![image](https://github.com/AlexxIT/WebRTC/assets/7027842/3f72f0f4-47e3-4ead-8b8b-cc5734eb47ce)

I then upgraded to v1.6.1, didn't modify anything, and now the HA card gives this error: `can't update URL for doorbell_main`

![image](https://github.com/AlexxIT/WebRTC/assets/7027842/27d98597-cd0d-4c08-81c0-92b2c519e577)

Any advice? I'm going back to 1.6.0 for now...
