### ISSUE TITLE
"muted: false" no longer working 

### ISSUE THREAD

**Issue by criticallimit** [AlexxIT/WebRTC#540]
Don´t know since when the "muted" is no longer working, but no matter if muted is set to true or false, it´s always muted and has to be set in the card manually

```yaml
type: custom:webrtc-camera
url: rtsp://192.168.178.10:8554/Essen?video=all&audio=opus
ui: true
title: null
muted: false
background: false
intersection: 0.4
mode: webrtc
```
