### ISSUE TITLE
Icons color for shortcuts does not change

### ISSUE THREAD

**Issue by eerison** [AlexxIT/WebRTC#548]
Hello the icon color for shortcuts are not changing when switch between `on` and `off`

```yaml
type: custom:webrtc-camera
url: camera_1_sala
ui: true
background: true
shortcuts:
  services:
    - name: Light
      icon: mdi:lightbulb
      service: switch.toggle
      service_data:
        entity_id: switch.cameras

```
