### ISSUE TITLE
ERROR: NotSupportedError : Filed to execute 'addSourceBuffer' on 'MediaSource'

### ISSUE THREAD

**Issue by Bastiencc** [AlexxIT/WebRTC#560]
Hi

I use some Tapo c210. Everything was ok, but since some week I get this error on my OnePlus 5 (using HA Android Apps) : 
`ERROR: NotSupportedError : Filed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="undefined"') is unsupported.`
![Screenshot_20230830-193251](https://github.com/AlexxIT/WebRTC/assets/37021892/b8d171f1-80a1-45fa-9213-6bcb7566bca7)

It is ok on my computer : 
![Capture d'écran 2023-08-30 193249](https://github.com/AlexxIT/WebRTC/assets/37021892/d6639416-b321-448c-9ea2-8697413c3c79)

this is the code (with the first card it is ok) : 
```
              - type: 'custom:button-card'
                template: custom_card_camera
                entity: camera.camerasalonhdrtsp
                show_icon: false #True if you set ulm_custom_card_camera_title: true
                variables:
                  ulm_custom_card_camera_title: true
                  ulm_custom_card_camera_name: "Salon"
                  ulm_custom_card_camera_label: ""
                  
              - type: 'custom:webrtc-camera'
                entity: camera.camerasalonhdrtsp
                title: Salon 
                poster: /local/img/splash.png  # still image when stream is loading
                muted: true  # disable sound, default true
                ui: true  # custom video controls, default false
                background: true  # run stream when not displayed (ex. for quick video loading), default false
                ptz:
                  service: button.press
                  data_left:
                    entity_id: button.camera_salon_move_left
                  data_right:
                    entity_id: button.camera_salon_move_right
                  data_up:
                    entity_id: button.camera_salon_move_up
                  data_down:
                    entity_id: button.camera_salon_move_down
```

thanks for your help !
