### ISSUE TITLE
Missing `url` or `entity` when trying to use multiple streams v3.3.0

### ISSUE THREAD

**Issue by reflexsa** [AlexxIT/WebRTC#565]
When trying to use this format:
```
type: 'custom:webrtc-camera'
streams:
  - url: go2rtc_stream_hd
    name: HD     # name is optional
    mode: webrtc # mode is optional
  - url: go2rtc_stream_sd
    name: SD
    mode: mse
```

I receive "Missing `url` or `entity`" when configuring the card. The url does work and functions as expected using the single stream format, eg:
```
type: 'custom:webrtc-camera'
url: 'rtsp://rtsp:12345678@192.168.1.123:554/av_stream/ch0'
```
Perhaps there is something in my url that it no longer recognizes it as one (maybe equals signs?). Below is an example of one of my urls:
`rtsp://admin:password@192.125.100.123:554/chID=8&streamType=sub&linkType=tcp`

Thank you for any help or advice.
