### ISSUE TITLE
Reolink Doorbell with two-way audio?! (no issue, just  info request)

### ISSUE THREAD

**Issue by pickonedev** [AlexxIT/WebRTC#582]
Hi!

Anyone have manage to achieve the two-way audio with a reolink doorbell without problems?
If yes, can you please share the code of the card.

Thank you!

**Comment by can-I-do** [comment]
I would also be very interested... I tried several configs and  didn't get it to work. On top I  don't have any sound now from the stream -.- 
using this atm:
`type: custom:webrtc-camera
ui: true
streams:
  - url: rtsp://HomA:Infakt66!@192.168.178.122:554/h264Preview_01_sub
    name: 😶
    background: false
    muted: false
    mic: false
    mode: webrtc
  - url: rtsp://HomA:Infakt66!@192.168.178.122:554/h264Preview_01_sub
    name: 🎙️
    background: false
    muted: false
    mic: true
   ### media: video,audio,microphone ### or do i need this line?
    mode: webrtc
    `

**Comment by can-I-do** [comment]
I would also be very interested... I tried several configs and didn't get it to work. On top I don't have any sound now from the stream -.-
using this atm:
```
type: custom:webrtc-camera
ui: true
streams:
  - url: rtsp://USER:PW@IP:554/h264Preview_01_sub
    name: 😶
    background: false
    muted: false
    mic: false
    mode: webrtc
  - url: rtsp://USER:PW@IP:554/h264Preview_01_sub
    name: 🎙️
    background: false
    muted: false
    mic: true
    ### media: video,audio,microphone ### or do i need this line?
    mode: webrtc
```

**Comment by daxcore** [comment]
Yeah, i guess i got it. 

```
type: custom:webrtc-camera
server: https://go2rtc.example.com/
streams:
  - url: reolink
    mode: webrtc
    media: video,audio
    name: 🔇
  - url: reolink
    mode: webrtc
    media: video,audio,microphone
    name: 🔈
ui: true
muted: false
```

go2rtc:
```
streams:
  reolink:
    - rtsp://admin:password@192.168.178.8:554/Preview_01_sub
    - "ffmpeg:reolink#audio=opus#audio=volume#async"

ffmpeg:
  bin: ffmpeg
  volume: "-af \"volume=25dB\""

```

reverse proxy:
```
server {
    server_name go2rtc.example.com;

    listen 80;

    if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }

    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;
    ssl_certificate /ssl/fullchain.pem;
    ssl_certificate_key /ssl/privkey.pem;

    ssl_dhparam /data/dhparams.pem;

    listen 443 ssl http2;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    proxy_buffering off;

    location / {
        proxy_pass http://homeassistant.local:1984;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```

**Comment by pickonedev** [comment]
@daxcore  Hi! Can you please explain what you wrote there, like you would explain it to a noob? :-D 
I only understand the first code which represents a webrtc-camera card, but what about the next two codes? What are, how, where? :-)

Thank you in advance!

**Comment by can-I-do** [comment]
If everything else works for you you just need the first part:
```
type: custom:webrtc-camera
server: https://go2rtc.example.com/
streams:
  - url: reolink
    mode: webrtc
    media: video,audio
    name: 🔇
  - url: reolink
    mode: webrtc
    media: video,audio,microphone
    name: 🔈
ui: true
muted: false
```
This part should somehow similar already be in your go2rtc.yaml, but not needed if you add the url directly into the card, like I did in my previous post:
```
streams:
  reolink:
    - rtsp://admin:password@192.168.178.8:554/Preview_01_sub
    - "ffmpeg:reolink#audio=opus#audio=volume#async"

ffmpeg:
  bin: ffmpeg
  volume: "-af \"volume=25dB\""
``` 

So the trick seems to be this line `media: video,audio,microphone`, no need for `mic: true`. The mic is working, evertheless it seems that I  don't have any sound coming back -.-

**Comment by pickonedev** [comment]
Thank you, I will try it today <3

**Comment by pickonedev** [comment]
Still... I am asking myself... for this Two-Way thing, why you need two streams? Ok, ok, I understand that one is with microphone and the other is not, but would not be easier if you use only one stream, but you have a button to turn on/off the microphone? Like the speaker... click Mute/click UnMute, could not this microphone have a similar usability?

@AlexxIT  ? Is this not possible? Sorry if maybe I transform a "question" post into a "feature request", first I just ask to know more.

Thanks

**Comment by AlexxIT** [comment]
Two separate streams is good design because you take and release mic not only on browser, but also on camera

**Comment by daxcore** [comment]
lets have a look to the readme.md file: 

> [Two-way audio](https://github.com/AlexxIT/WebRTC#two-way-audio)
> 
> * Only for [supported sources](https://github.com/AlexxIT/go2rtc#two-way-audio) in go2rtc
> * Only for Hass with HTTPS access, this limitation is [from the browsers](https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https)
> * Only for WebRTC mode
> * HTTPS is also important for Hass Mobile App!
> 
> You should add microphone to media param. You can use two streams: one with mic, second without:
> 
> ```
> type: 'custom:webrtc-camera'
> streams:
>   - url: go2rtc_stream
>   - url: go2rtc_stream
>     mode: webrtc
>     media: video,audio,microphone
> ```

for 2-way audio, `https` is the key. that's why, i posted my nginx reverse proxy configuration. i guess, if the `server: https://go2rtc.example.com/` in your card code will not refer to https url, it will not work!

**Comment by pickonedev** [comment]
This is what I try to use in my card

```
type: custom:webrtc-camera
ui: true
muted: false
streams:
  - url: rtsp://admin:Acountinx123H@192.168.0.92:554/h264Preview_01_sub
    mode: webrtc
    media: video,audio
    name: 🔇
  - url: rtsp://admin:Acountinx123H@192.168.0.92:554/h264Preview_01_sub
    mode: webrtc
    media: video,audio,microphone
    name: 🔈
```

The go2rtc I think it is already installed in HA, no need for external server.
HA it is configured to use HTTPS only accessed from outside, from LAN, it is accesed through HTTP...

**Comment by pickonedev** [comment]
This is what I try to use in my card

```
type: custom:webrtc-camera
ui: true
muted: false
streams:
  - url: rtsp://admin:pass@192.168.0.92:554/h264Preview_01_sub
    mode: webrtc
    media: video,audio
    name: 🔇
  - url: rtsp://admin:pass@192.168.0.92:554/h264Preview_01_sub
    mode: webrtc
    media: video,audio,microphone
    name: 🔈

```

**Comment by can-I-do** [comment]
after I added this stuff after and before "-->" to my go2rtc.yaml sound seems to work now
```
streams:
  reolink:
    - rtsp://admin:password@192.168.178.8:554/Preview_01_sub
    - "ffmpeg:reolink#audio=opus. --> #audio=volume#async" 

ffmpeg:
  bin: ffmpeg
  volume: "-af \"volume=25dB\""
<-- 
```
