### ISSUE TITLE
Add support for PTZ preset positions

### ISSUE THREAD

**Issue by carloslebreiro** [AlexxIT/WebRTC#60]
Hi, it would be nice to besides the up/down/left/right/zoom in/zoom out also to have the possibility to select presets (up to 6).
I'm using the PTZ service with the following data:
```
      action: call-service
      service: onvif.ptz
      service_data:
        entity_id: camera.mainprofile
        preset: Preset1
        speed: 1
        distance: 0.5
        move_mode: GotoPreset
```

**Comment by mgiako** [comment]
Hi, I like this integration.
PTZ presets would be the icing on the cake!
Actually I'm using picture-elements card with the same parameters as above.
is there any hope that they will be integrated?
Thanks in advance.

**Comment by sajikur** [comment]
PTZ or BUST! ;)

**Comment by wonderiuy** [comment]
+1 for this, cherry on cake

**Comment by hellcry37** [comment]
+ for this

**Comment by ecasp-hassio** [comment]
Totally agree, it would be the best have the possibility to use presets.

**Comment by wowgamr** [comment]
+1

**Comment by AlexxIT** [comment]
Latest integration version support shortcuts

**Comment by SuperMaximus1984** [comment]
@AlexxIT please help with creating a shortcut for PTZ camera preset:

In my webrtc custom card I have this shortcut:
```
shortcuts:
  - name: Home
    icon: mdi:home
    service: onvif.ptz
    data:
      preset: '2'
      move_mode: GotoPreset
    target:
      entity_id: camera.axis_q6125_le_profile_1_h264
```
While pressing the designated icon I get:
`Failed to call service onvif/ptz. must contain at least one of entity_id, device_id, area_id`

When a separate service execution with this code from HA Developer Tools runs smoothly:
```
service: onvif.ptz
data:
  preset: "2"
  move_mode: GotoPreset
target:
  entity_id: camera.axis_q6125_le_profile_1_h264
```

Tried to use without "target", receiving the same above error.
