### ISSUE TITLE
error="streams: codecs not matched: H264 => H264, H265, AAC"

### ISSUE THREAD

**Issue by swex** [AlexxIT/WebRTC#608]
At first I thought its related to https://github.com/AlexxIT/go2rtc/issues/711 or https://github.com/AlexxIT/go2rtc/issues/762, but killing got2rtc process does not help.
To recover failed streams I have to restart home assistant instance.
here is how it looks:
![image](https://github.com/AlexxIT/WebRTC/assets/1026241/0ce7c740-bd8f-4953-a4ce-18231d7a9175)

**Comment by AlexxIT** [comment]
You need to increase log level for go2rtc to trace and check them.

**Comment by swex** [comment]
After some investigation, I found that my old [cameras](https://falconeye.su/Products/392/71/FE-IPC-BL200PV/), become crazy after talking rtsp with go2rtc. Even ffprobe/ffplay gives me 'invalid data found when processing input' until I restart camera manually. 

Currently fixed by changing input to ffmpeg, it works for now.

**Comment by jkay90** [comment]
@swex can you please share details on your fix. 
I am also facing this problem with Tapo cameras

**Comment by swex** [comment]
sure, here is example config:
```yaml
streams:
  cam1:
    - ffmpeg:rtsp://login:$PASS@192.168.1.181:554/ch01.264?ptype=udp#video=copy
    # - rtsp://login:$PASS@192.168.1.181:554/ch01_sub.264?ptype=udp
log:
  level: trace # default level
ffmpeg:
  bin: /home/swex/bin/ffmpeg-6.1-amd64-static/ffmpeg
```
0. trace log level helps to investigate
1. I got updated ffmpeg and put path to ffmpeg binary in config
2. changed input from plain rtsp (commented in cfg example) to ffmpeg prefixed uri
