### ISSUE TITLE
Can´t use 2-Way Audio on Reolink App after used in WebRTC

### ISSUE THREAD

**Issue by Jack77777777** [AlexxIT/WebRTC#617]
Hi,

I implemented my Reolink Doorbell Wifi in Home Assistant trough go2rtc (Frigate).
But when i use the microphone stream (Sprechen) in HA it is no more possible through the Reolink App.
I tried with gortc 1.6.2 and 1.8.4.
HA and Frigate is installed in Docker on a Synology DS718+.
After a reboot of the Doorbell i can use the 2-Way Audio in the App until i use it again in HA.

HA Card:
type: custom:webrtc-camera
streams:
  - url: reolink
    name: Stumm
    mode: webrtc
    media: video
  - url: reolink
    name: Sprechen
    mode: webrtc
    media: video,audio,microphone
ui: true

Home Assitant 2023.11.2
Frigate 0.12.1
go2rtc 1.8.4
WebRTC Camera 3.5.0

**Comment by AlexxIT** [comment]
Maybe better to write Reolink developers?

**Comment by Jack77777777** [comment]
> Maybe better to write Reolink developers?

I opened a ticket at Reolink. But i don't think it's an Reolink issue. Did some more investigation. The 2 way audio seems to be blocked/still active in frigate. After reboot of frigate i can use the app. How can i change from frigate go2rtc to the implemented go2rtc of webrtc?

**Comment by AlexxIT** [comment]
If you keep an active connection to the speaker via go2rtc - it's not a go2rtc or Reolink problem. It's your problem. You shouldn't be doing this. You can open go2rtc WebUI and check all active connections.

**Comment by Jack77777777** [comment]
@AlexxIT I just read your comment here https://github.com/AlexxIT/WebRTC/issues/582#issuecomment-1768135706 and agree i configured it wrong. But i don´t know how to do it right. How can i create a stream with and one without mic  in the frigate/go2rtc config?

**Comment by AlexxIT** [comment]
Start from this

> You can open go2rtc WebUI and check all active connections

**Comment by AlexxIT** [comment]
You should also check producers. If it takes sendonly media (for two way audio).

**Comment by Jack77777777** [comment]
@AlexxIT I am not sure what to look for. I made screenshots.

**Before Frigate restart:**
![image](https://github.com/AlexxIT/WebRTC/assets/64719909/f6ffcf82-68e9-45d9-b536-69c0a2954c07)

After Frigate restart i can access 2-way audio with reolink app.

**go2rtc after opening stream:**
****  - url: reolink
    name: Stumm
    mode: webrtc
    media: video
![image](https://github.com/AlexxIT/WebRTC/assets/64719909/9df017a5-7f6d-4dad-87fc-f37c7be52184)

**go2rtc after opening stream:**
  - url: reolink
    name: Sprechen
    mode: webrtc
    media: video,audio,microphone
![image](https://github.com/AlexxIT/WebRTC/assets/64719909/e06f662e-b2a3-4b44-b72c-cdd7cb5e8ef9)

No more 2-way audio through reolink app possible.

**Comment by Jack77777777** [comment]
Do you mean the yellow highlighted sendonly?
![image](https://github.com/AlexxIT/WebRTC/assets/64719909/fd23ddd8-8a33-4199-8ba6-ea8d0a4f3a17)

**Comment by AlexxIT** [comment]
Please read Amcrest Doorbell recommendation. I think Reolink has same problem:
https://github.com/AlexxIT/go2rtc#source-rtsp

**Comment by Jack77777777** [comment]
> Please read Amcrest Doorbell recommendation. I think Reolink has same problem: https://github.com/AlexxIT/go2rtc#source-rtsp
Changed my config to:
```
go2rtc:
  streams:
    reolink:
      - rtsp://user:password@192.168.178.82:554/h264Preview_01_sub#backchannel=0
      - ffmpeg:reolink#audio=opus
cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.178.82:554/h264Preview_01_sub#backchannel=0
```
Now 2-way audio in app works always but i can not use in home assistant, what makes sense because i disabled by adding `#backchannel=0`.
So actually 2-way audio with reolink/amcrest is only possible in app or home assistant, not both ?

**Comment by AlexxIT** [comment]
WebRTC card allows you to set different streams. One with mic and second without.

**Comment by Jack77777777** [comment]
> WebRTC card allows you to set different streams. One with mic and second without.

Can you help me because i am not sure if i have to configure the two streams in go2rtc or WebRTC Card.
My actual go2rtc/frigate config is in my last post.
My WebRTC Config:
```
type: custom:webrtc-camera
streams:
  - url: reolink
    name: Stumm
    mode: webrtc
    media: video
  - url: reolink
    name: Sprechen
    mode: webrtc
    media: video,audio,microphone
ui: true
muted: false
```

**Comment by Jack77777777** [comment]
I think i understood now. I will try when i am at home again and report here.

**Comment by Jack77777777** [comment]
@AlexxIT I think i got it working now.
Below just for reference of my working config for Reolink Doorbell Wifi

**frigate/go2rtc:**
mqtt:
  host: IP_of_MQTTServer
  port: 1883
  
```
go2rtc:
  streams:
    reolink_nomic:
      - rtsp://user:password@IP_of_Cam:554/h264Preview_01_sub#backchannel=0
      - ffmpeg:rtsp://user:password@IP_of_Cam:554/h264Preview_01_sub#audio=opus
    reolink_mic:
      - rtsp://user:password@IP_of_Cam:554/h264Preview_01_sub
      - ffmpeg:rtsp://user:password@IP_of_Cam:554/h264Preview_01_sub#audio=opus

## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@IP_of_Cam:554/h264Preview_01_sub
```

**WebRTC Card:**
```
type: custom:webrtc-camera
streams:
  - url: reolink_nomic
    name: Stumm
    mode: webrtc
    media: video
  - url: reolink_mic
    name: Sprechen
    mode: webrtc
    media: video,audio,microphone
```
BTW:
I had the issue of dropping connection when Cam was activated in Synology Surveillance.
With the firmware v3.0.0.2153_23051501 and above config the Doorbell works with HA, Reolink App and Synology
