### ISSUE TITLE
Feature Request: Privacy mode - blur & dim picture based on a boolean entity

### ISSUE THREAD

**Issue by alexruffell** [AlexxIT/WebRTC#624]
When showing my Home Assistant Dashboard to others, or sharing it online, I prefer to blur out the camera feeds. 

Using the picture-glance card, this is how I was achieving it:
```
type: picture-glance
title: Driveway - East
entities:
  - entity: input_boolean.driveway_east_camera_privacy
camera_image: camera.driveway_east_camera
aspect_ratio: '16:9'
camera_view: live
state_filter:
  'on': brightness(40%) blur(10px) saturate(0.0)
  'off': brightness(100%)
entity: input_boolean.driveway_east_camera_privacy
```

Example of the privacy mode:
![image](https://github.com/AlexxIT/WebRTC/assets/4006944/5263cc88-5192-448b-8e91-657290c37008)

Now that I am using the webrtc-camera card I can't find a way to do it.
```
type: custom:webrtc-camera
entity: camera.driveway_east_camera
poster: camera.driveway_east_camera
title: East
media: video,audio
muted: true
digital_ptz:
  mouse_drag_pan: false
  mouse_wheel_zoom: false
  mouse_double_click_zoom: false
  touch_drag_pan: false
  touch_pinch_zoom: false
  touch_tap_drag_zoom: false
  persist: false
```

Would you kindly consider adding this feature?
