### ISSUE TITLE
Ability to add icon rather than text for various url streams

### ISSUE THREAD

**Issue by TurboTronix** [AlexxIT/WebRTC#628]
Is there a way to give us the ability to add a different icon for each of the streams?

For example I have the following which is a combination of 2 streams, one with mic on and one with mic off. I want to be able to display a mic on icon and a mic off icon rather than just text.

![image](https://github.com/AlexxIT/WebRTC/assets/7071554/a3a43f44-e0ee-4fc3-9299-b69d497c7f42)

```
type: custom:webrtc-camera
ui: true
streams:
  - url: reolink_doorbell
    name: Mic OFF
  - url: reolink_doorbell
    mode: webrtc
    media: video,audio,microphone
    name: Mic ON
style: >-
  video {object-fit: fill;} .pictureinpicture {display: none} .header {display:
  none} .stream { font-size: 15px; width: 150px;  font-weight: bold;
  padding-left: 2px;}
```

**Comment by AlexxIT** [comment]
Use emoji

**Comment by TurboTronix** [comment]
What would be the code? Can you show me an example?

**Comment by TurboTronix** [comment]
Ok got it but they don't have mic off icon :|

```
type: custom:webrtc-camera
ui: true
streams:
  - url: reolink_doorbell
    name: 🔇
  - url: reolink_doorbell
    mode: webrtc
    media: video,audio,microphone
    name: 🔊
style: >-
  video {object-fit: fill;} .pictureinpicture {display: none} .header {display:
  none}
```
