### ISSUE TITLE
Unable to create streams for google nest camera entities - `no entity_id`

### ISSUE THREAD

**Issue by twhittock** [AlexxIT/WebRTC#635]
Trying to use go2rtc using this integration to create a stream for the my google nest camera so I can use it in more places.

Following the readme to configure it using hass entities (which are working directly in hass) in the go2rtc docs here: https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-hass

I create a configuration like this:

    streams:
      left_side_camera:
        - hass:entity_id=camera.left_side_camera

No errors on startup, but when I try to preview the stream using http://myhassinstance:1984/stream.html?src=left_side_camera I get the following error:

`undefined error=streams: hass: no entity_id caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166`

Looking at go2rtc issues, this was reported before and was due to missing config info, but I can't see any way / need to do that when running as an integration?

**Comment by twhittock** [comment]
If i should be using the different syntax in the readme in this repo, I'm a bit confused.

If I use `hass://supervisor?entity_id=camera.left_side_camera` then I get the error `undefined error=streams: hass: wrong type: auth_invalid caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166`

If I use `hass://myhassinstance?entity_id=camera.left_side_camera` then I get `undefined error=streams: hass: no token caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166`

So it's like it needs to treat the request as if it's an external system, even though it's running as an integration?

**Comment by Lockie85** [comment]
I'm also getting this issue with my Nest Doorbell camera. Go2RTC is installed on my Home Assistant as an Addon. The code is as follows:
```
streams:
  bedroom_2:
    - hass:Camera-Hub-G3-E44E
    - ffmpeg:aqara_g3#audio=aac#audio=opus
  doorbell:
    - hass:doorbell
```
Worth noting that the bedroom_2 camera works fine.

**Comment by AlexxIT** [comment]
`hass:entity_id=camera.left_side_camera` syntax completely wrong.
How have you installed Hass?
How have you installed go2rtc?

**Comment by twhittock-disguise** [comment]
Yeah, I tried a lot of different variations on the syntax, since nothing I tried worked. The second message lists the variations.

Home Assistant is a simple hassos install, nothing special.

go2rtc is installed via this integration, which I relied on to install go2rtc (which works for other camera types) My configuration is:

```
api:
  password: <password>
  username: admin
rtsp:
  password: <password>
  username: admin
hass:
  config: "/config"
streams:
  <other cameras which work...>
  nest_camera:
    - hass://supervisor?entity_id=camera.left_side_camera&token=<my token>
```

**Comment by twhittock** [comment]
Yeah, I tried a lot of different variations on the syntax, since nothing I tried worked. The second message lists the variations.

Home Assistant is a simple hassos install, nothing special.

go2rtc is installed via this integration, which I relied on to install go2rtc (which works for other camera types) My configuration is:

```
api:
  password: <password>
  username: admin
rtsp:
  password: <password>
  username: admin
hass:
  config: "/config"
streams:
  <other cameras which work...>
  nest_camera:
    - hass://supervisor?entity_id=camera.left_side_camera&token=<my token>
```
