### ISSUE TITLE
Feature Request: Documentation for Roborock PTZ control

### ISSUE THREAD

**Issue by dscarr10** [AlexxIT/WebRTC#637]
Was not sure how to add this or where to send this example to get it added but I figured I would submit my example of Roborock PTZ controls using the Roborock custom integration here:

**Roborock PTZ controls**

Integration - [https://github.com/humbertogontijo/homeassistant-roborock](url)

```
ptz:
  service: roborock.vacuum_remote_control_move
  data_left:
    duration: 0
    rotation: 30
    velocity: 0
    entity_id: vacuum.tank
  data_right:
    duration: 0
    rotation: -30
    velocity: 0
    entity_id: vacuum.tank
  data_up:
    duration: 1000
    rotation: 0
    velocity: 0.29
    entity_id: vacuum.tank
  data_down:
    duration: 1000
    rotation: 0
    velocity: -0.29
    entity_id: vacuum.tank
```
