### ISSUE TITLE
WebRTC Card fails randomly to load on Safari

### ISSUE THREAD

**Issue by vuminhkh** [AlexxIT/WebRTC#646]
Hello,

I'm using WebRTC camera v3.5.1 on HomeAssistant, my configuration lovelace is the following:

```
  - title: Visiophone
    path: visiophone
    icon: mdi:phone
    badges: []
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.visio_phone
            live_provider: webrtc-card
            webrtc_card:
              mode: webrtc
              media: video,audio,microphone
        menu:
          position: bottom
```

my configuration Frigate

```
    visio_phone:
      - rtsp://usr:pwd@visio_phone.internal:554/Streaming/channels/101#backchannel=0
      - isapi://usr:pwd@visio_phone.internal:80/
```

My doorbell Hikvision DS-KB8113-IME1 (B)

On chrome, it works very well, on Safari, it fails randomly to load the camera and when it fails, Safari freezes completely and don't respond anymore, no other solution than to close and reopen. On my Mac, I can use chrome to workaround the issue, but on my iphone companion app, it's Safari and it seems that there's no way to change this, it makes the card not usable. Could you please take a look ?
