### ISSUE TITLE
Tapo PTZ example for wiki (button press)

### ISSUE THREAD

**Issue by mattaustin** [AlexxIT/WebRTC#655]
## Tapo

[Integration](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control)

```yaml
type: custom:webrtc-camera
streams:
  - entity: camera.cameraname_hd_stream
    mode: webrtc
muted: true
ptz:
  service: button.press
  data_left:
    entity_id: button.cameraname_move_left
  data_right:
    entity_id: button.cameraname_move_right
  data_up:
    entity_id: button.cameraname_move_up
  data_down:
    entity_id: button.cameraname_move_down
```
