### ISSUE TITLE
Add some way to toggle client microphone (Two-Way Audio camera)

### ISSUE THREAD

**Issue by lorenzomartini1** [AlexxIT/WebRTC#656]
It would be nice to add something to toggle client microphone to the webrtc-camera card.

To enable microphone I add `microphone` to:
`media: video,audio,microphone`
and this is working, but microphone is always on.

but it would be usefull to choose when enable or disable client microphone.

My HA card config:
```
type: custom:webrtc-camera
url: cam_gatto
ui: true
digital_ptz:
  mouse_drag_pan: true
  mouse_wheel_zoom: true
  mouse_double_click_zoom: true
  touch_drag_pan: true
  touch_pinch_zoom: true
  touch_tap_drag_zoom: true
  persist: true
mode: webrtc
media: video,audio,microphone
ptz:
  service: button.press
  data_left:
    entity_id: button.camera_di_lore_move_left
  data_right:
    entity_id: button.camera_di_lore_move_right
  data_up:
    entity_id: button.camera_di_lore_move_up
  data_down:
    entity_id: button.camera_di_lore_move_down

```
