### ISSUE TITLE
webrtc.create_link generates 'Integer exceeds 64-bit range' error

### ISSUE THREAD

**Issue by Scoff123** [AlexxIT/WebRTC#657]
I am using the webrtc.create_link service, in the following script:
```
variables:
    link_id: "{% for _ in range(40) %}{{ range(10)|random }}{% endfor %}"
  sequence:
    - service: webrtc.create_link
      data:
        link_id: "{{ link_id }}"
        entity: camera.front_doorbell_sub
        open_limit: 1
        time_to_live: 120
```
When running the script,  I get a warning error logged:
```
TypeError: Integer exceeds 64-bit range
```

As an example, this is a link ID that is generated with the above, and the attached warning indicating the Integer exceeds 64-bit range
```
Event is not JSON serializable: <Event call_service[L]: domain=webrtc, service=create_link, service_data=link_id=9515413525586482336294872353385819779842, entity=camera.front_doorbell_sub, open_limit=1, time_to_live=120>: Integer exceeds 64-bit range
```

A previous ticket [#421 ](https://github.com/AlexxIT/WebRTC/issues/421) received the reply "Looks like link_id not string but integer. You need to use quotes." 

Can you explain exactly where quotes are required in order to regard the ID as a string? I have quotes in my link_id code above, but perhaps they need to be altered? Thanks
