### ISSUE TITLE
WebRTC Dashcast Nest Google Hub stops working

### ISSUE THREAD

**Issue by adoreparler** [AlexxIT/WebRTC#661]
I have a Google Nest Hub and Home Assistant and also WebRTC Installed.
My Cameras are Ubiquiti cameras and in the options for the camera I turned on RTSPS Link for High Definition.

I created a script:
```yaml
alias: Streaming Outside Camera to Kitchen Display
sequence:
  - service: webrtc.dash_cast
    data:
      entity_id: media_player.kitchen_display
      url: rtspx://11.0.0.71:7441/{UniqueIdentifierWasHere}
      force: true
mode: single
icon: mdi:webcam
```

When I tell the google hub the alias above it starts displaying and I can see the camera feed with about a 2 - 3 second lag. But after about 5 seconds the stream goes black and does not load back up. If I close out and say the alias again it works again for about 5 seconds and the stream goes black.

I turned on Debug logging but I am not sure where to go to see the debug logging. I went to system -> Logs and dont see anything in there around WebRTC.
