### ISSUE TITLE
Refreshing the poster on a specified interval

### ISSUE THREAD

**Issue by infectedroot** [AlexxIT/WebRTC#662]
In my setup, I'm trying to set up WebRTC like my Generic Cameras where the static image from the camera is pulled in on a regular basis and displayed on screen, and I can tap the mode or source labels to view the video on-demand.

While I have the video-on-demand part down, when on the poster view, the image doesn't update on a regular basis. I need to refresh the entire screen for the image to load.

I've scoured the docs to find a command that'll refresh the poster image on a regular basis, but I cannot find it. 

Below is my setup for reference... could anyone tell me if this is possible with WebRTC, or has this issue become a feature request?

```
type: custom:webrtc-camera
poster: http://10.8.0.9:5000/snapshot/west-side-front.jpg
streams:
  - url: ''
  - url: rtsp://03cabcc9-ring-mqtt:8554/9c76138a550e_live
ui: true
```
