### ISSUE TITLE
PTZ movements and zoom sensitivity adjustment

### ISSUE THREAD

**Issue by SuperMaximus1984** [AlexxIT/WebRTC#673]
Please add up setting PTZ sensitivity.
Using on-screen controls results in too high sensitivity, making it impossible to control camera movements accurately (it moves too far, zooms too much using one on-screen keypress).
Is there a way to set smaller camera movements using OSD controls?

type: custom:webrtc-camera
entity: camera.axis_q6125_le_profile_1_h264
```
ptz:
  service: onvif.ptz
  data_left:
    entity_id: camera.axis_q6125_le_profile_1_h264
    pan: LEFT
  data_right:
    entity_id: camera.axis_q6125_le_profile_1_h264
    pan: RIGHT
  data_up:
    entity_id: camera.axis_q6125_le_profile_1_h264
    tilt: UP
  data_down:
    entity_id: camera.axis_q6125_le_profile_1_h264
    tilt: DOWN
  data_zoom_in:
    entity_id: camera.axis_q6125_le_profile_1_h264
    zoom: ZOOM_IN
  data_zoom_out:
    entity_id: camera.axis_q6125_le_profile_1_h264
    zoom: ZOOM_OUT
```
