### ISSUE TITLE
[Feature Request] Two-way push to talk with secondary stream

### ISSUE THREAD

**Issue by kantlivelong** [AlexxIT/WebRTC#685]
Hello,

I'm currently using an AMCrest AD410 where the `#backchannel=0` fragment is required in order for the call button to work. What I've done so far is create 3 separate streams in go2rtc and WebRTC which are SD, HD, and now SD-MIC. 

What would be neat is if WebRTC Camera could use the `doorbell_sd_2way` outside of the streams toggle button and instead allow the user to either touch a button or touch the video stream to activate the `doorbell_sd_2way` stream with two way audio only while either `doorbell_sd` or `doorbell_hd` were in view. The user would essentially be activating a hidden audio only stream on touch. If possible this would work around the backchannel issue as well as make the two way experience better. The initial push to talk action would likely need some kind of feedback indicating that the stream is being opened vs when push to talk is actually awaiting audio input. After some timeout the stream could automatically close.

#### go2rtc
```yaml
streams:
  doorbell_hd: rtsp://USER:PASSWORD@HOST/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#backchannel=0
  doorbell_sd: rtsp://USER:PASSWORD@HOST/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif#backchannel=0
  doorbell_sd_2way: rtsp://USER:PASSWORD@HOST/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif#backchannel=1
```
#### WebRTC Camera
```yaml
streams:
  - url: doorbell_sd
    name: SD
  - url: doorbell_hd
    name: HD
  - url: doorbell_sd_2way
    name: SD-MIC
    media: video,audio,microphone
```

#### go2rtc
```yaml
streams:
  doorbell_hd: rtsp://USER:PASSWORD@HOST/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#backchannel=0
  doorbell_sd: rtsp://USER:PASSWORD@HOST/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif#backchannel=0
  doorbell_sd_2way: rtsp://USER:PASSWORD@HOST/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif#backchannel=1
  # ^ I'm not sure if there is a way to request an audio only RTSP stream but if not go2rtc can handle it as usual while WebRTC Camera perhaps could request audio only
```
#### WebRTC Camera
```yaml
streams:
  - url: doorbell_sd
    name: SD
    media: 
  - url: doorbell_hd
    name: HD
  - url: doorbell_sd_2way
    name: TWO WAY
    media: microphone # microphone only streams could be omitted from the stream selection toggle.
microphone_mode: pushtotalk # pushtotalk|always or something of the sort
```

Thanks!

**Comment by kantlivelong** [comment]
Curious as to why, could you elaborate?

**Comment by AlexxIT** [comment]
Current behavior is very clear and transparent. We always know when the camera's microphone is busy and when it's not. For some cameras, " occupy microphone" is a big problem. The user is not allowed to "occupy the microphone" from two different locations at the same time.

**Comment by kantlivelong** [comment]
Ah okay that makes sense.

Thanks :smile:

**Comment by johnmathews** [comment]
I ran into this while setting up a Reolink doorbell and ended up building a working push-to-talk mode for this card. It addresses this issue, #750 and #584, and I'd be happy to submit it as a PR if there's interest. Config:

```yaml
type: 'custom:webrtc-camera'
url: doorbell
media: video,audio,microphone
ptt: true
```

What it does:

- Renders a **Hold to talk** button below the video. The microphone is captured and transmitted **only while the button is held** (`sender.replaceTrack(track)` / `replaceTrack(null)` + `track.stop()`), so the browser's recording indicator is off while idle — today the card keeps the mic hot for as long as the stream is open.
- While transmitting, the card's own audio is muted (half-duplex) so you don't hear your voice echoed back through the camera's microphone ~1s later.
- **Fixes two-way audio on iOS**: WebKit rejects `getUserMedia` outside a user gesture, and the card currently requests the mic during negotiation (async, no gesture) and only `console.warn`s the failure — which I believe is why two-way audio fails silently on iPhone for many people. With `ptt: true` the mic is requested inside the button press; if negotiation happened without an audio sender, the first press grants permission and reconnects ("hold again to talk" shown once).
- getUserMedia errors (no HTTPS, permission denied) are shown on the card instead of only in the console.

Implementation is ~150 lines, entirely in `webrtc-camera.js` (no changes to the vendored `video-rtc.js`), following the existing `render*()` pattern. Tested on Firefox/Chrome desktop and the iOS companion app against a Reolink doorbell through go2rtc.

Unrelated but possibly useful for others landing here with Reolink doorbells: if talkback works once and then never again until go2rtc restarts, add `#backchannel=0` to the *main* stream so talkback uses the dedicated sub-stream session — otherwise talkback senders accumulate on the permanent main RTSP session and the camera's single talkback channel wedges.

**Comment by CaptInsano** [comment]
> I ran into this while setting up a Reolink doorbell and ended up building a working push-to-talk mode for this card. It addresses this issue, [#750](https://github.com/AlexxIT/WebRTC/issues/750) and [#584](https://github.com/AlexxIT/WebRTC/issues/584), and I'd be happy to submit it as a PR if there's interest. Config:
> 
> type: 'custom:webrtc-camera'
> url: doorbell
> media: video,audio,microphone
> ptt: true
> What it does:
> 
> * Renders a **Hold to talk** button below the video. The microphone is captured and transmitted **only while the button is held** (`sender.replaceTrack(track)` / `replaceTrack(null)` + `track.stop()`), so the browser's recording indicator is off while idle — today the card keeps the mic hot for as long as the stream is open.
> * While transmitting, the card's own audio is muted (half-duplex) so you don't hear your voice echoed back through the camera's microphone ~1s later.
> * **Fixes two-way audio on iOS**: WebKit rejects `getUserMedia` outside a user gesture, and the card currently requests the mic during negotiation (async, no gesture) and only `console.warn`s the failure — which I believe is why two-way audio fails silently on iPhone for many people. With `ptt: true` the mic is requested inside the button press; if negotiation happened without an audio sender, the first press grants permission and reconnects ("hold again to talk" shown once).
> * getUserMedia errors (no HTTPS, permission denied) are shown on the card instead of only in the console.
> 
> Implementation is ~150 lines, entirely in `webrtc-camera.js` (no changes to the vendored `video-rtc.js`), following the existing `render*()` pattern. Tested on Firefox/Chrome desktop and the iOS companion app against a Reolink doorbell through go2rtc.
> 
> Unrelated but possibly useful for others landing here with Reolink doorbells: if talkback works once and then never again until go2rtc restarts, add `#backchannel=0` to the _main_ stream so talkback uses the dedicated sub-stream session — otherwise talkback senders accumulate on the permanent main RTSP session and the camera's single talkback channel wedges.



I was looking through the issues looking for something like this.

The current setup of two streams; one with microphone and one without does not really work in my use-case and often microphone audio is just left steaming to the camera (tapo in this case)

My current card is set up like this:

```
type: custom:webrtc-camera
ui: true
muted: false
mode: webrtc
background: true
  streams:
    - url: Cam_sub
       name:  Mic OFF
       media: video,audio
    - url: Cam_sub
       name:  Mic ON
       media: video,audio,microphone
```

@johnmathews , I would be interested in testing your implementation of a push-to-talk button. 
Do you have a fork of this repo with the changes to test?
