### ISSUE TITLE
webrtc-camera custom card and api

### ISSUE THREAD

**Issue by Nik71git** [AlexxIT/WebRTC#696]
Hi, my webrtc-camera custom card is configured as below:

```
type: custom:webrtc-camera
server: http://192.168.xxx.xxx:1984/
streams:
  - url: cam1
  - url: ''
title: terrazzo
media: video
mode: webrtc
ui: true
poster: /local/cctv.png
intersection: 0.25
```

and api section on go2rtc config file as below:
```
api:
  listen: ":1984"  
  username: ""  # default "", but I prefer auth for WebUI
  password: ""   # default "", but I prefer auth for WebUI
```
when I add credentials on api section webrtc-camera card stop working, how can I specify credentials on it?
