### ISSUE TITLE
Crashing iOS app switching stream 

### ISSUE THREAD

**Issue by Martinvdm** [AlexxIT/WebRTC#724]
When changing from stream to allow 2 way audio, the IOS companion app is crashing. It takes some seconds but at the end it become unresponsive.
The seconds stream is followed by the manual to allow selectable 2 way audio and in the first place without. 

Config Lovelace:
```
- type: 'custom:webrtc-camera'
    server: http://localhost:1984/
    title: camera.voordeur_go2rtc
    streams:
      - url: camera.voordeur
        name: 🔇      # name is optional
        mode: webrtc  # mode is optional
        media: video,audio  # media is optional
      - url: camera.voordeur
        name: 🔊
        mode: webrtc
        media: video,audio,microphone
        muted: false
    ui: true
    muted: true
    background: true
```

Go2rtc config:

```
streams:
  camera.voordeur:
    - rtsp://admin:xxxx@172.19.3.3:554/Streaming/channels/102
    - isapi://admin:xxxx@172.19.3.3:65001/

```

most of the time the first try is working fine. After switching again it hangs by selecting the second stream on black screen ‘loading’
And at the end iOS app become unresponsive and disconnects.

nothing really special in logging. Go2rtc log is clean. Home assistant log only new connection:
`
2024-07-02 20:50:14.443 DEBUG (MainThread) [custom_components.webrtc] New client: {'authSig': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI5NWU1MWE2Yjc2ZGE0MmI0YWM2NDQxYzc5ZjNmMDM4NyIsInBhdGgiOiIvYXBpL3dlYnJ0Yy93cyIsInBhcmFtcyI6W10sImlhdCI6MTcxOTk0NjIxNCwiZXhwIjoxNzE5OTQ2MjQ0fQ.HHYmydw0qOkRTO14MGz5tf6zjpWZ7kwANBRR0ekmdaM', 'url': 'camera.voordeur', 'server': 'http://localhost:1984/'}
`

companion app logging is also empty.
In non ui mode it happens also. Resulting in loading and at the end app disconnect.
![IMG_2939](https://github.com/AlexxIT/WebRTC/assets/1952661/a10fb1c2-a8a0-4b57-a90d-f8c6a734daf3)

backend: Hikvision nvr with isapi camera and 2 way audio.
