### ISSUE TITLE
The state of a switch is not represented in a shortcut

### ISSUE THREAD

**Issue by Pirol62** [AlexxIT/WebRTC#731]
![image](https://github.com/user-attachments/assets/9d65b23d-0f0d-4583-8cb6-98eb0d7e53cb)
Both switches are off at this time
````
  - name: push
    icon: mdi:message
    action: call-service
    service: switch.toggle
    service_data:
      entity_id: switch.e1_eingang_push_benachrichtigungen
  - name: record
    icon: mdi:record
    action: call-service
    service: switch.toggle
    service_data:
      entity_id: switch.e1_eingang_aufzeichnen
````
