### ISSUE TITLE
Card title

### ISSUE THREAD

**Issue by kei81131** [AlexxIT/WebRTC#738]
For the card "title", if it is possible to show an entity state? 
like using template

**Comment by codemunkie15** [comment]
You can use the config-template-card as a workaround to use templates in the config of any card.

https://github.com/iantrich/config-template-card

 ```
 - type: custom:config-template-card
    entities:
      - sensor.wiser_lts_temperature_nursery
    card:
      type: custom:webrtc-camera
      url: nursery_camera
      title: ${states['sensor.wiser_lts_temperature_nursery'].state}
```
