### ISSUE TITLE
Feature Request: Notification when stream is currently watching

### ISSUE THREAD

**Issue by Miloune** [AlexxIT/WebRTC#759]
Hello,

I'm not sure if I should ask this here or on camera integration, but is it possible to have one entity or something else which is updated if the stream is watching by someone.
The scenario / automation could be:
- Someone connecting to HA
- Go on Webcam tab and start watching live stream
- Entity camera_watching is updated to "true"
- Automation triggered
- Notification sent

Or maybe something that call service in the card directly:
```
type: custom:webrtc-camera
entity: camera.camera
on_start:
   action: send-notification
   data: ...
on_stop:
   action: send-notification
   data: ...
```

If it's not possible or not the good place to post, feel free to close this feature request.
