### ISSUE TITLE
3.6.0: Shorcuts missing

### ISSUE THREAD

**Issue by requies** [AlexxIT/WebRTC#760]
After the upgrade from 3.5.2 to 3.6.0 my shortcuts went missing.
Reverting to 3.5.2 fixes the problem.

3.5.2
![pre](https://github.com/user-attachments/assets/9a829a82-96c7-4e43-9dc5-33b82e35eb00)

3.6.0
![post](https://github.com/user-attachments/assets/c4d72e67-59c0-486d-b9ea-b91a5e0b888b)

Card yaml:

```
type: custom:webrtc-camera
url: ptz_50x
ui: true
shortcuts:
  services:
    - name: Color
      icon: mdi:lightbulb
      service: select.select_option
      service_data:
        entity_id: select.ptz_50x_day_night_color
        option: Color
    - name: Color light
      icon: mdi:lightbulb-on
      service: select.select_option
      service_data:
        entity_id: select.ptz_50x_day_night_color
        option: Color light
    - name: IR LED
      icon: mdi:lightbulb-alert-outline
      service: select.select_option
      service_data:
        entity_id: select.ptz_50x_day_night_color
        option: IR LED
    - name: IR LED, light on alert
      icon: mdi:lightbulb-alert
      service: select.select_option
      service_data:
        entity_id: select.ptz_50x_day_night_color
        option: IR LED, light on alert
    - name: Sync
      icon: mdi:clock-check
      service: icsee_ptz.synchronize_clock
      service_data:
        entity_id: binary_sensor.ptz_50x_motion_alarm
    - name: Force frame
      icon: mdi:play
      service: icsee_ptz.force_frame
      service_data:
        entity_id: binary_sensor.ptz_50x_motion_alarm
    - name: FocusNear
      icon: mdi:image-filter-center-focus-strong-outline
      service: icsee_ptz.move
      service_data:
        entity_id: binary_sensor.ptz_50x_motion_alarm
        cmd: FocusNear
    - name: FocusFar
      icon: mdi:image-filter-center-focus
      service: icsee_ptz.move
      service_data:
        entity_id: binary_sensor.ptz_50x_motion_alarm
        cmd: FocusFar
    - name: FocusStop
      icon: mdi:focus-field
      service: icsee_ptz.move
      service_data:
        entity_id: binary_sensor.ptz_50x_motion_alarm
        cmd: Stop
ptz:
  service: icsee_ptz.move
  data_home:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: GotoPreset
    preset: 0
  data_long_home:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: SetPreset
    preset: 0
  data_start_left:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: DirectionLeft
  data_end_left:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: Stop
  data_start_right:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: DirectionRight
  data_end_right:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: Stop
  data_start_down:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: DirectionDown
  data_end_down:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: Stop
  data_start_up:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: DirectionUp
  data_end_up:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: Stop
  data_start_zoom_in:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: ZoomTile
  data_end_zoom_in:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: Stop
  data_start_zoom_out:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: ZoomWide
  data_end_zoom_out:
    entity_id: binary_sensor.ptz_50x_motion_alarm
    cmd: Stop
digital_ptz:
  mouse_drag_pan: true
  mouse_wheel_zoom: true
  mouse_double_click_zoom: true
  touch_drag_pan: true
  touch_pinch_zoom: true
  touch_tap_drag_zoom: true
  persist: true
```
