### ISSUE TITLE
No video from SV3C camera in HA

### ISSUE THREAD

**Issue by sergeolkhovik** [AlexxIT/WebRTC#768]
Hi! I've got 3 cameras from SV3C (https://sv3c.aliexpress.com/store/5720035) and before installing them I checked RTSP stream and I could play it via ffplay without any issue (the URL is like rtsp://192.168.1.x/0 or rtsp://user:pass@192.168.1.x/0).
One camera shows well in HA via simple card:
```
type: custom:webrtc-camera
url: rtsp://cam6.domain/0
```
while 2 other cameras show nothing:

![image](https://github.com/user-attachments/assets/2f87fb6a-abce-4d39-a0d6-1bd3a43db742)

Again, I tested those cameras with ffplay (and VLC) and RTSP stream is OK. Moreover, all those 3 cameras are captured by kerberos.io agents (on another host, DVR). HA is running on RPi 3 in core mode (PVE + service).
In addition I tried to setup go2rtc on DVR host via docker:
```
  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: always
    privileged: true
    ports:
      - "1984:1984"
      - "8554:8554"  # RTSP port (optional, if you need RTSP access)
      - "8555:8555"  # WebRTC
#      - "8888:8888"
#    network_mode: host
    environment:
      - TZ=${AGENT_TIMEZONE}
    volumes:
      - "/usr/local/src/kerberos.io/go2rtc:/config"
```
with go2rtc/go2rtc.yaml as:
```
streams:
  cam7:
    - rtsp://cam7.domain/0
  cam8:
    - rtsp://user:pass@cam8.domain/0
```
and none of the links that I can see at http://dvr:1984 works, the same black screen.
Can you please help me how to debug this and dig more info to figure out what's wrong?
I don't see any logs in HA log file or syslog, and see nothing in container as well:
```
go2rtc           | 13:52:19.296 INF go2rtc platform=linux/amd64 revision=a4885c2 version=1.9.4
go2rtc           | 13:52:19.304 INF config path=/config/go2rtc.yaml
go2rtc           | 13:52:19.306 INF [api] listen addr=:1984
go2rtc           | 13:52:19.306 INF [rtsp] listen addr=:8554
go2rtc           | 13:52:19.307 INF [webrtc] listen addr=:8555/tcp
```
