### ISSUE TITLE
Touch pinch zoom also activates fullscreen in HA Companion App on iOS

### ISSUE THREAD

**Issue by LeChuck2909** [AlexxIT/WebRTC#771]
Hi,

up to recently, i was able to use the touch pinch zoom from the digital ptz. I had the card exclusively in a dashboard and did not enter fullscreen, as this in iOS forces you to either watch any video either not zoomed at all or at only one zoom level. Thus without fullscreen i was able to use touch pinch zoom and appreciated it very much like that.

Lately when i tried to touch pinch zoom, the digital zoom is happening, but also the video is going into full screen. This is very bothersome, as in fullscreen i can not zoom freely as mentioned above.

When i leave then fullscreen again, the video is zoomed according to the finger movement i did before it went into full screen, but paused ... then i need to drag until i find the play button and press play to have my digital zoom.

So to summarize in my amateur words: since recently the pinch gesture suddenly initiates both, the touoch_pinch_zoom feature from this card and the fullscreen from iOS.

Unfortunately I dont know when exactly this started ... it might have started with the release 3.6

sorry for my vague report. thank you!

here is my config:
```
type: custom:webrtc-camera
entity: camera.kids_cam
persist: false
poster: camera.reo_kids_fliessend
background: false
muted: false
digital_ptz:
  mouse_drag_pan: false
  mouse_wheel_zoom: false
  mouse_double_click_zoom: true
  touch_drag_pan: true
  touch_pinch_zoom: true
  touch_tap_drag_zoom: false
ptz:
  service: onvif.ptz
  data_left:
    entity_id: camera.kids_cam_onvif_profile000_mainstream
    pan: LEFT
    move_mode: ContinuousMove
  data_right:
    entity_id: camera.kids_cam_onvif_profile000_mainstream
    pan: RIGHT
    move_mode: ContinuousMove
  data_up:
    entity_id: camera.kids_cam_onvif_profile000_mainstream
    tilt: UP
    move_mode: ContinuousMove
  data_down:
    entity_id: camera.kids_cam_onvif_profile000_mainstream
    tilt: DOWN
    move_mode: ContinuousMove
  data_zoom_in:
    entity_id: camera.kids_cam_onvif_profile000_mainstream
    zoom: ZOOM_IN
    move_mode: ContinuousMove
  data_zoom_out:
    entity_id: camera.kids_cam_onvif_profile000_mainstream
    zoom: ZOOM_OUT
    move_mode: ContinuousMove
style: >
  .screenshot {display: none} .pictureinpicture {display: none} .ptz {right:
  unset; top: 100px} .mode {display: none}

```
