### ISSUE TITLE
Lovelace card only up to 4 cameras maximum?

### ISSUE THREAD

**Issue by kingp0dd** [AlexxIT/WebRTC#774]
I am casting a dashboard to chromecast through:

```
action: cast.show_lovelace_view
data:
  entity_id: media_player.chromecast
  dashboard_path: dashboard-y
  view_path: camtest
```
At first, it shows all 12 camera thumbnails, then it will refresh the page after 2 seconds, and then only 4 camera streams will be left playing. The rest of the cards show the following error:

"Failed to start WebRTC stream..."

![image](https://github.com/user-attachments/assets/0346fe0c-b5cc-4455-bbbb-9c71d8e16a3a)
