### ISSUE TITLE
Cameras don't automatically upgrade to RTC despite being capable of it

### ISSUE THREAD

**Issue by MattJeanes** [AlexxIT/WebRTC#775]
Hey, I've been seeing a weird issue in my Home Assistant install for a while where my cameras seem to want to only go over MSE, despite RTC being fully supported end-to-end. I don't know exactly when this started but when I originally set up the integration probably well over a year ago now it was working fine and upgrading to RTC.

This is evidenced by if I explicitly set `mode: webrtc` or `mode: webrtc/tcp` it works fine and says RTC in the top right corner but if I remove the mode setting or set it to something like `mode: webrtc,webrtc/tcp,mse,hls,mjpeg` it always settles for MSE for some reason:

![image](https://github.com/user-attachments/assets/0d717b37-3ccb-40de-baee-97972467aada)

Running over HTTPS connection to HA via Chrome 131 on Windows 11 23H2, and also happens on Android 15 on Pixel 8 Pro (also over HTTPS). It also does it over HTTP via both homeassistant.local and the direct IP to HA.

Checked developer console of browser and debug integration logs - nothing interesting in there.

Happens even with the most basic configuration of the card:

```yaml
type: custom:webrtc-camera
url: front_garden_camera_left_sub
```

or more complex ones:

```yaml
type: custom:webrtc-camera
poster: front_garden_camera_left_jpeg
streams:
  - url: front_garden_camera_left_sub
    name: SD
  - url: front_garden_camera_left_main
    name: HD
ui: true
muted: true
digital_ptz:
  mouse_double_click_zoom: false
  touch_tap_drag_zoom: false
  persist: false
```

Relevant info from go2rtc.yaml (sensitive info redacted):
```yaml
api:
  password: <redacted>
  username: admin
rtsp:
  password: <redacted>
  username: admin
streams:
  front_garden_camera_left_sub: http://192.168.68.95/flv?user=stream&password=<redacted>&port=1935&app=bcs&stream=channel0_sub.bcs
  front_garden_camera_left_main: http://192.168.68.95/flv?user=stream&password=<redacted>&port=1935&app=bcs&stream=channel0_main.bcs
  front_garden_camera_left_jpeg: http://192.168.68.95/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=Get&user=stream&password=<redacted>&width=640&height=360
```

Happens with all my cameras which are all one of:
- Reolink CX410 
- Reolink Video Doorbell WiFi
- Reolink RLC-520A
- Reolink E1 Zoom

If you need any more info from me please let me know!

**Comment by AlexxIT** [comment]
You have Reolink cameras. They using AAC audio codec. It's supported only in MSE mode. This card will prefer technology with video+audio:
- https://github.com/AlexxIT/go2rtc/blob/master/api/README.md
- https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#codecs-madness

**Comment by MattJeanes** [comment]
> Technology selection based on priorities:
> 
> Video and Audio better than just Video
> H265 better than H264
> WebRTC better than MSE, than HLS, than MJPEG

That explains it - thank you!

Is it worth / a good idea to use ffmpeg in the go2rtc config to transcode the audio to Opus/PCMA/PCMU?

Something like:

```yaml
streams:
  front_garden_camera_left_sub: ffmpeg:http://192.168.68.95/flv?user=stream&password=<redacted>&port=1935&app=bcs&stream=channel0_sub.bcs#video=copy#audio=opus
```

Putting the MSE and RTC streams side by side definitely seems to have better latency / slightly smoother but I would like the retain the audio support indeed - but I am not sure about the negatives / downsides of doing this, assuming it would even work.

**Comment by AlexxIT** [comment]
This version will work better
```yaml
streams:
  reolink1:
    - http://...
    - ffmpeg:reolink1#audio=opus
```
