### ISSUE TITLE
Only works internal. Cannot make it work from internet

### ISSUE THREAD

**Issue by Pammetje** [AlexxIT/WebRTC#777]
I cannot make webrtc-camera working from the internet side becaus of NAT
I opened and forwarded TCP/UDP 8555 from my firewall to my internal Home Assitants IP
I got this in go2rtc.yaml
```
webrtc:
  listen: ":8555/tcp"
  candidates:
    - _my_fixed_public_ip_:8555 
```

It is not clear from the documentation if I should forward an UDP port range from my Home Assistant IP to the internet
