### ISSUE TITLE
Add Template/Example: Aqara G3 [with Node-RED] hack

### ISSUE THREAD

**Issue by sectune** [AlexxIT/WebRTC#802]
I would like to thank you for your amazing projects and contribute a template/example for the Aqara G3 cam (using go2rtc and the Node-RED PTZ hack / AqaraPOST-Homeassistant addon]:

```
ptz:
     service: button.press
     data_left:
         entity_id: button.camera_g3_ptz_left
…
```
Analogous to the Tapo example. Maybe you could also link to the GitHub repo AqaraPOST-Homeassistant addon of sdavides.
Thank you once more!
