### ISSUE TITLE
Unable to get two way audio working

### ISSUE THREAD

**Issue by Jebarson** [AlexxIT/WebRTC#804]
I have go2rtc running out of frigate. I am setting up a webrtc card in HA for a 2-way audio. However, when switching to the audio option by clicking "MSE", it goes on to loading and stays there.

Below is what my card setting look like

```
type: custom:webrtc-camera
streams:
  - url: Doorbell_HQ
  - url: Doorbell_HQ
    mode: webrtc
    media: video, audio, microphone
```

I am able to browse the go2rtc server installed in the frigate without issue and also watch the stream.

Below is how my card looks.

![Image](https://github.com/user-attachments/assets/1f346806-2458-476c-bf26-221177e49199)

View after I click the MSE in the above view

![Image](https://github.com/user-attachments/assets/98538824-24fc-402d-ace0-f666e9f5f902)
