### ISSUE TITLE
Microphone on/off toggle switch

### ISSUE THREAD

**Issue by m1tchy24** [AlexxIT/WebRTC#818]
I'm aware that there is the ability to change streams (and have an ugly emoji button)
however would it be possible to add a button with can toggle on/off the microphone without switching streams?

**Comment by AlexxIT** [comment]
I don't plan on this, because every extra feature increases the code and complicates support.
But I'll leave it in case there are a lot of suggestions or someone wants to implement it on their own.

PS. Turning off the microphone by switching the stream is not a simple wish. In this way, it is possible to implement microphone release for different camera protocols, for which it is important that the microphone is free when not in use. Disabling the microphone in the browser will not help in this task.

**Comment by netsoft-ruidias** [comment]
I have a suggestion here: https://github.com/AlexxIT/WebRTC/issues/898

**Comment by webysther** [comment]
> I don't plan on this, because every extra feature increases the code and complicates support. But I'll leave it in case there are a lot of suggestions or someone wants to implement it on their own.
> 
> PS. Turning off the microphone by switching the stream is not a simple wish. In this way, it is possible to implement microphone release for different camera protocols, for which it is important that the microphone is free when not in use. Disabling the microphone in the browser will not help in this task.

Will be nice to have this option when using the `mode: ui` because this exists for sound and open a popup without the change to turn on/off the mic.

Today:

```yaml
show_state: false
show_name: false
camera_view: live
fit_mode: fill
type: picture-entity
entity: camera.interfone_2
grid_options:
  rows: 4
  columns: 12
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Interfone
      content:
        type: entities
        entities:
          - type: custom:webrtc-camera
            url: doorbell
            ui: true
            mode: webrtc
            media: video,audio,microphone
            style: ".pictureinpicture, .screenshot, .fullscreen {display: none}"
```

Result:

<img width="431" height="306" alt="Image" src="https://github.com/user-attachments/assets/267ed986-aa4d-44d9-a76a-b75fce74d665" />

Future:

Add in bottom a mic icon to turn on/off.
