### ISSUE TITLE
WebRTC Card - full screen button using a different stream?

### ISSUE THREAD

**Issue by RBDaniel** [AlexxIT/WebRTC#820]
Is there a way to use WebRTC for the regular card mode but switch to an MSE stream when I click the full screen button?

My camera's _main channel is in h265 and only supports MSE and the _sub is in h264, so I have to use it because it's the only one that supports full WebRTC, which in turn allows 2-way audio.

I could insert an MSE stream and flip to it, then hit full screen but it would be more convenient if it would do it on its own without breaking my 2-way audio. I just thought it would be cool to hit the full screen button and use the higher resolution stream vs the pixelated _sub stream.

```
type: custom:webrtc-camera
streams:
  - url: Parking
    mode: webrtc
    name: 🎙️
  - url: Parking
    mode: webrtc
    media: video,microphone
    name: 🔴
ui: true
muted: true
background: true
style: >
  video {aspect-ratio: 16/9; object-fit: 100%;} .mode {display: none}
  .screenshot {display: none}
```
