### ISSUE TITLE
Channel button top position not in line on ui buttons

### ISSUE THREAD

**Issue by jonyrh-td-sever** [AlexxIT/WebRTC#836]
Hello!

Core 2025.5.1
Supervisor 2025.05.0
Operating System 15.2
User interface 20250509.0
WebRTC Camera and go2rtc last versions on 2025-05-13

Channel button top position not in line on ui buttons:

![Image](https://github.com/user-attachments/assets/4a8ab895-040c-4486-8926-945d2daefb6a)

```yaml
type: custom:webrtc-camera
ui: true
muted: false
style: "video {object-fit: fill} .mode {display: none}"
streams:
  - url: Tapo_C110_SD
    name: SD
    mode: webrtc
    media: video
  - url: Tapo_C110_HD
    name: HD
    mode: webrtc
    media: video,audio
layout_options:
  grid_columns: 4
  grid_rows: 2
```
PS: delete `layout_options:` section does not affect
