### ISSUE TITLE
Eufy doorbell P2P not producing audio

### ISSUE THREAD

**Issue by MastaG** [AlexxIT/WebRTC#844]
I've installed Eufy Security 8.2.1 and WebRTC 3.6.0 using HACS.
I'm using the builtin go2rtc version 1.9.4.

I've added a camera card for my Eufy Doorbell:
```
type: custom:webrtc-camera
entity: camera.deurbel
media: video,audio
poster: image.deurbel_event_image
ui: true
shortcuts:
  - name: Play
    icon: mdi:play
    service: camera.turn_on
    service_data:
      entity_id: camera.deurbel
  - name: Stop
    icon: mdi:stop
    service: camera.turn_off
    service_data:
      entity_id: camera.deurbel
```

Now when I activate the camera using the play button I can see the camera showing up in go2rtc.
The config looks like:
```
streams:
  T821451024144503: T821451024144503
```

But when I look at the stream info, it only seems to produce a single H264 steam:
```
{
  "producers": [
    {
      "url": "T821451024144503"
    },
    {
      "id": 188,
      "format_name": "h264",
      "medias": [
        "video, recvonly, H264"
      ],
      "receivers": [
        {
          "id": 190,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 50,
            "profile": "High"
          },
          "childs": [
            191,
            193
          ],
          "bytes": 3564571,
          "packets": 891
        }
      ],
      "bytes_recv": 4566839
    }
  ],
  "consumers": [
    {
      "id": 189,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "192.168.0.162:49324",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=64c032;sprop-parameter-sets=Z2TAMqwbGqBkARX5ZuAgICgAAAMACAAAAwD0eEQjUA==,aO8xshs=\r\na=control:trackID=0\r\n",
      "user_agent": "FFmpeg Frigate/0.15.0-6cb5cfb",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        {
          "id": 191,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 50,
            "profile": "High"
          },
          "parent": 190,
          "bytes": 3564571,
          "packets": 891
        }
      ],
      "bytes_send": 3617317
    },
    {
      "id": 192,
      "format_name": "probe",
      "protocol": "http",
      "remote_addr": "192.168.0.30:41756",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "senders": [
        {
          "id": 193,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 50,
            "profile": "High"
          },
          "parent": 190
        }
      ]
    }
  ]
}
```

What's up with that?
I'd also like to record the audio as well.
