### ISSUE TITLE
How to send audio to go2rtc camera?

### ISSUE THREAD

**Issue by aik** [AlexxIT/WebRTC#850]
I have HASS with WebRTC and Frigate 0.16 + whatever go2rtc goes with it. I can watch videos in HA from Frigate, all good.
Now I want to send a doorbell sound to a camera. I am reading WebRTC doc:
```
media_player:
  - platform: webrtc
    name: Driveway Camera
    stream: driveway
    audio: pcmu/48000
```
and, say, my camera in frigate is:
```
go2rtc:
  streams:
    driveway:
      - rtsp://shitcam:554/user=admin&password=&channel=&stream=.sdp?real_stream--rtp-caching=100
      - ffmpeg:driveway#audio=aac
      - isapi://admin@shitcam:80/ # <- for two-way audio
```
HA says about "Driveway Camera" casting entity "unavailable".
Is it misconfiguration in Frigate? Or HA is missing an addon/integration?

The camera is some Hikvision. A working config example is what I am after here. Thanks!
