### ISSUE TITLE
Stream does not start on 3.6.0 if inside conditional card with background: true

### ISSUE THREAD

**Issue by JurajNyiri** [AlexxIT/WebRTC#851]
When switching tabs inside Home Assistant, stream does not start if:

- Background: true
- Card inside conditional card

Replication steps:

1. Create following view in Home Assistant dashboard

```
type: sections
max_columns: 4
title: tmp2
path: tmp2
sections:
  - type: grid
    cards:
      - type: heading
        icon: mdi:cancel
        heading: Does not work
        heading_style: title
      - type: conditional
        conditions:
          - condition: state
            entity: camera.living_room_sd
            state_not: irrelevant
        card:
          type: custom:webrtc-camera
          background: true
          entity: camera.living_room_sd
  - type: grid
    cards:
      - type: heading
        icon: mdi:clipboard-check
        heading: Works
        heading_style: title
      - type: custom:webrtc-camera
        background: true
        entity: camera.living_room_sd
```

2. Open another tab
3. Refresh browser
4. Click into newly created tmp2 view
5. Observe stream on the left not loading

Of course, replace `camera.living_room_sd` first with some real entity that usually works via webrtc.

My use case and how I discovered this:

If my frigate instance is running, I am using advanced-camera-card, which contains the webrtc card, but with the additional elements to interact with frigate.
If my frigate instance is not running, I expose the webrtc stream directly, otherwise I would have no stream because there would be an error shown from advanced camera card.

Fix that got it solved for me - not sure if this is the proper way to fix this;

1. Uncomment line https://github.com/AlexxIT/WebRTC/blob/c8b69d3b5dd85fc1831fe0c45454d9fd73f547d0/custom_components/webrtc/www/webrtc-camera.js#L81 .
2. (Optional, did not contribute to fix, but felt like the right thing) Comment https://github.com/AlexxIT/WebRTC/blob/c8b69d3b5dd85fc1831fe0c45454d9fd73f547d0/custom_components/webrtc/www/webrtc-camera.js#L79
