### ISSUE TITLE
High cpu usages from go2rtc 1.9.4

### ISSUE THREAD

**Issue by Sorien** [AlexxIT/WebRTC#855]
there is problem with high cpu usage from go2rtc at version 1.9.8 and below, and latest version of this addon still downloads version 1.9.4, Moreover there seems to be some incompatibility when I try to replace 1.9.4 with 1.9.9 when getting just black screen instead of picture from camera how to force this addon to use newest version of go2rtc?

I've tried to update addon manually but still no picture, hikvision cameras
```
type: custom:webrtc-camera
streams:
  - url: rtsp://admin:mypassword@192.168.1.65:554/Streaming/Channels/103
    name: HD
  - url: rtsp://admin:mypassword@192.168.1.65:554/Streaming/Channels/101
    name: QHD
```

ws stream ends with this 

![Image](https://github.com/user-attachments/assets/19dd2fc1-f3bb-4a4c-a399-c11bf8e38e8a)
