### ISSUE TITLE
Uncaught TypeError: Cannot read property 'callService' of undefined

### ISSUE THREAD

**Issue by gomble** [AlexxIT/WebRTC#90]
If i add onvif ptz i get the following error if i click left right etc.:

```
Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190
First occurred: 11:54:32 (14 occurrences)
Last logged: 11:59:29

https://---:8123/webrtc/webrtc-camera.js?v2.0.2:332:22 Uncaught TypeError: Cannot read property 'callService' of undefined
```

my card:
```
type: custom:webrtc-camera
url: ---
ui: true
background: true
ptz:
  service: onvif.ptz
  data_left:
    entity_id: camera.onvif_camera_profile_001
    pan: LEFT
  data_right:
    entity_id: camera.onvif_camera_profile_001
    pan: RIGHT
  data_up:
    entity_id: camera.onvif_camera_profile_001
    tilt: UP
  data_down:
    entity_id: camera.onvif_camera_profile_001
    tilt: DOWN
  data_zoom_in:
    entity_id: camera.onvif_camera_profile_001
    zoom: ZOOM_IN
  data_zoom_out:
    entity_id: camera.onvif_camera_profile_001
    zoom: ZOOM_OUT
```

PTZ works with manual service call like this:
```
   tap_action:
      action: call-service
      service: onvif.ptz
      service_data:
        entity_id: camera.onvif_camera_profile_001
        pan: RIGHT
        distance: 0.41
        speed: 0.5
        continuous_duration: 0.5
        move_mode: ContinuousMove
```
