### ISSUE TITLE
Error stream with dashcast

### ISSUE THREAD

**Issue by fingalo** [AlexxIT/WebRTC#97]
Sorry, I found the reason for this.
Either use url OR entity in data:
Did a rtfm and a light turned on...

Hello.
First, many thank's for webrtc, so very good!

I'm trying to cast my camera to Chromecast using webrtc.dash_cast.
I've created a simple script in script Gui.

Tested with my camera stream and bunny stream.
Also tested in services tab, same issues

```
sequence:
  - service: webrtc.dash_cast
    data:
      entity_id: media_player.tv
      url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
      entity: camera.c200_minorstream
mode: single
alias: Cam1casttv

```
I get then following error in log:
021-06-21 21:09:33 ERROR (MainThread) [homeassistant.components.script.cam1casttv] Cam1casttv: Error executing script. Invalid data for call_service at pos 1: two or more values in the same group of exclusion 'url' @ data[<url>]_

I've successfully streamed the camera to Chromecast using HA cast (with the bad lagging on the screen).
